In [1]:
!pip3 install indic-nlp-library

Collecting indic-nlp-library
  Downloading indic_nlp_library-0.92-py3-none-any.whl.metadata (5.7 kB)
Collecting sphinx-argparse (from indic-nlp-library)
  Downloading sphinx_argparse-0.5.2-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: sphinx-rtd-theme in /usr/local/lib/python3.11/dist-packages (from indic-nlp-library) (0.2.4)
Collecting morfessor (from indic-nlp-library)
  Downloading Morfessor-2.0.6-py3-none-any.whl.metadata (628 bytes)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from indic-nlp-library) (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from indic-nlp-library) (1.26.4)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy->indic-nlp-library) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy->indic-nlp-library) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy->indic-nlp-library) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy->indic-nlp-library) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy->indic-nlp-library) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy->indic-nlp-library) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->indic-nlp-library) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->indic-nlp-library) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->indic-nlp-library) (2025.2)
Requirement already satisfied: sphinx>=5.1.0 in /usr/local/lib/python3.11/dist-packages (from sphinx-argparse->indic-nlp-library) (8.2.3)
Requirement already satisfied: docutils>=0.19 in /usr/local/lib/python3.11/dist-packages (from sphinx-argparse->indic-nlp-library) (0.21.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->indic-nlp-library) (1.17.0)
Requirement already satisfied: sphinxcontrib-applehelp>=1.0.7 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp>=1.0.6 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.1.0)
Requirement already satisfied: sphinxcontrib-jsmath>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp>=1.0.6 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: Jinja2>=3.1 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.1.6)
Requirement already satisfied: Pygments>=2.17 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.19.2)
Requirement already satisfied: snowballstemmer>=2.2 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.0.1)
Requirement already satisfied: babel>=2.13 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.17.0)
Requirement already satisfied: alabaster>=0.7.14 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.0)
Requirement already satisfied: imagesize>=1.3 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.4.1)
Requirement already satisfied: requests>=2.30.0 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.32.4)
Requirement already satisfied: roman-numerals-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.1.0)
Requirement already satisfied: packaging>=23.0 in /usr/local/lib/python3.11/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (25.0)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy->indic-nlp-library) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy->indic-nlp-library) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy->indic-nlp-library) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy->indic-nlp-library) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy->indic-nlp-library) (2024.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from Jinja2>=3.1->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2025.6.15)
Downloading indic_nlp_library-0.92-py3-none-any.whl (40 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 kB 1.3 MB/s eta 0:00:00
Downloading Morfessor-2.0.6-py3-none-any.whl (35 kB)
Downloading sphinx_argparse-0.5.2-py3-none-any.whl (12 kB)
Installing collected packages: morfessor, sphinx-argparse, indic-nlp-library
Successfully installed indic-nlp-library-0.92 morfessor-2.0.6 sphinx-argparse-0.5.2

In [2]:
import pandas as pd
import numpy as np
from transformers import AutoTokenizer
import torch 
from indicnlp.tokenize import indic_tokenize

In [3]:

data=pd.read_csv("/kaggle/input/sample-dataset/Sentence pairs in English-Hindi - 2025-02-11.tsv",sep="\t",header=None,names=["SrcSent ID","SrcSent","DstSentID","DstSent"])

In [4]:
data.head()

,SrcSent ID,SrcSent,DstSentID,DstSent
0,1282,Muiriel is 20 now.,485968,म्यूरियल अब बीस साल की हो गई है।
1,1282,Muiriel is 20 now.,2060319,म्यूरियल अब बीस साल की है।
2,1294,Education in this world disappoints me.,485564,मैं इस दुनिया में शिक्षा पर बहुत निराश हूँ।
3,1302,That won't happen.,2060320,वैसा नहीं होगा।
4,1308,I miss you.,2060321,मुझें तुम्हारी याद आ रही है।

In [5]:
data.shape

(13182, 4)

In [6]:
data.drop(labels=[data.columns[0],data.columns[2]],axis=1,inplace=True)

In [7]:
data.head()

,SrcSent,DstSent
0,Muiriel is 20 now.,म्यूरियल अब बीस साल की हो गई है।
1,Muiriel is 20 now.,म्यूरियल अब बीस साल की है।
2,Education in this world disappoints me.,मैं इस दुनिया में शिक्षा पर बहुत निराश हूँ।
3,That won't happen.,वैसा नहीं होगा।
4,I miss you.,मुझें तुम्हारी याद आ रही है।

In [8]:
src_sent_tokenizer=AutoTokenizer.from_pretrained("google-T5/T5-base")

config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [9]:
data["SrcSent"]=data["SrcSent"].apply(lambda x: src_sent_tokenizer.tokenize(x))

In [10]:
data.head()

,SrcSent,DstSent
0,"[▁Mu, i, riel, ▁is, ▁20, ▁now, .]",म्यूरियल अब बीस साल की हो गई है।
1,"[▁Mu, i, riel, ▁is, ▁20, ▁now, .]",म्यूरियल अब बीस साल की है।
2,"[▁Education, ▁in, ▁this, ▁world, ▁disappoint, ...",मैं इस दुनिया में शिक्षा पर बहुत निराश हूँ।
3,"[▁That, ▁won, ', t, ▁happen, .]",वैसा नहीं होगा।
4,"[▁I, ▁miss, ▁you, .]",मुझें तुम्हारी याद आ रही है।

In [11]:
data["DstSent"]=data["DstSent"].apply(lambda x: indic_tokenize.trivial_tokenize(x,lang="hi"))

In [12]:
data.head()

,SrcSent,DstSent
0,"[▁Mu, i, riel, ▁is, ▁20, ▁now, .]","[म्यूरियल, अब, बीस, साल, की, हो, गई, है, ।]"
1,"[▁Mu, i, riel, ▁is, ▁20, ▁now, .]","[म्यूरियल, अब, बीस, साल, की, है, ।]"
2,"[▁Education, ▁in, ▁this, ▁world, ▁disappoint, ...","[मैं, इस, दुनिया, में, शिक्षा, पर, बहुत, निराश..."
3,"[▁That, ▁won, ', t, ▁happen, .]","[वैसा, नहीं, होगा, ।]"
4,"[▁I, ▁miss, ▁you, .]","[मुझें, तुम्हारी, याद, आ, रही, है, ।]"

In [13]:
data["SrcSent"]=data["SrcSent"].apply(src_sent_tokenizer.convert_tokens_to_ids)

In [14]:
data.head()

,SrcSent,DstSent
0,"[4159, 23, 14018, 19, 460, 230, 5]","[म्यूरियल, अब, बीस, साल, की, हो, गई, है, ।]"
1,"[4159, 23, 14018, 19, 460, 230, 5]","[म्यूरियल, अब, बीस, साल, की, है, ।]"
2,"[2855, 16, 48, 296, 26963, 7, 140, 5]","[मैं, इस, दुनिया, में, शिक्षा, पर, बहुत, निराश..."
3,"[466, 751, 31, 17, 1837, 5]","[वैसा, नहीं, होगा, ।]"
4,"[27, 3041, 25, 5]","[मुझें, तुम्हारी, याद, आ, रही, है, ।]"

In [15]:
Vs=src_sent_tokenizer.get_vocab()

In [16]:
Vs

{'modificarea': 28377,
 '▁malpractice': 29758,
 '▁compliment': 12064,
 'ecţia': 26964,
 '▁propre': 6999,
 'L': 434,
 '▁burning': 9706,
 '▁sufficient': 6684,
 'gebracht': 10350,
 '▁authoritative': 30838,
 '▁CRM': 16966,
 'zentrum': 16476,
 '▁Für': 2513,
 '▁mega': 13950,
 'loc': 5133,
 '▁proaspat': 29752,
 '▁makes': 656,
 '▁politicians': 13446,
 '▁refuz': 19352,
 '▁augment': 15189,
 'engraved': 27799,
 '▁conduce': 21255,
 '▁Herren': 22683,
 'Avem': 22859,
 'colour': 24814,
 '▁schlimm': 27125,
 '▁Charleston': 19018,
 'approche': 12571,
 '▁Her': 1347,
 'ubb': 21207,
 'lenk': 19070,
 '▁medicul': 25386,
 'ionism': 28740,
 '▁Civil': 7707,
 '▁subscribers': 17303,
 'är': 3185,
 '▁pertain': 29580,
 '▁Tucson': 28226,
 '▁Watson': 18763,
 '▁William': 4599,
 'Assemblée': 29907,
 '▁cumpăra': 24245,
 'oul': 7115,
 '▁truly': 1892,
 '▁acceler': 25421,
 'klassischen': 25817,
 'oir': 5425,
 'trop': 12395,
 '▁reliabl': 28624,
 '▁Vorteile': 21731,
 '▁cooperation': 8494,
 'județul': 28413,
 '▁friction': 21764,
 '▁font': 4088,
 '▁würde': 6368,
 'ţa': 6249,
 'ified': 3676,
 'listened': 17010,
 'ţiuni': 16155,
 '▁primesc': 28500,
 'phobia': 27426,
 '▁crore': 23095,
 '▁Burn': 10846,
 '▁susțin': 29746,
 '▁renseignements': 28467,
 '▁Schlag': 20521,
 '▁Dual': 17338,
 'cellular': 10791,
 '▁phenomenon': 15037,
 '▁Fourth': 21670,
 '▁niche': 11276,
 'patented': 22370,
 'yahoo': 29057,
 'vita': 12411,
 'OTA': 27976,
 '▁(2006)': 28272,
 '1,000': 19215,
 '▁cogn': 23179,
 '▁penetrate': 24974,
 '▁bieten': 5180,
 '▁Black': 1589,
 '▁honest': 5057,
 'erster': 21735,
 '▁win': 1369,
 'überall': 22312,
 'agriculture': 28531,
 'itorul': 21570,
 '▁or': 42,
 'etti': 10652,
 'ност': 31585,
 '▁Museum': 3312,
 '▁comunicare': 19190,
 '▁patch': 7947,
 '▁consortium': 27754,
 '▁Final': 6514,
 '▁serrurier': 21515,
 '▁opinions': 8479,
 '▁pur': 3990,
 '▁glaci': 24414,
 'Several': 8656,
 '▁subscription': 7644,
 '▁aerial': 22142,
 '▁Mattress': 28302,
 '▁relative': 5237,
 '▁followers': 10076,
 '▁fiber': 6433,
 '▁Name': 5570,
 '▁$100': 10417,
 '▁Volk': 25963,
 '▁Eis': 16988,
 'IAL': 15397,
 'ovi': 9881,
 '▁cumparat': 18010,
 '▁vintage': 5917,
 '▁pamant': 25073,
 'ward': 2239,
 '▁Arbeiten': 18382,
 '▁Optimiz': 30543,
 '▁180': 8003,
 'hält': 10641,
 'RAM': 23203,
 '▁impartial': 30280,
 '▁exploit': 9248,
 '▁Direkt': 20980,
 '▁mortal': 24301,
 '▁demonstr': 13191,
 'QUI': 21672,
 '▁instances': 10316,
 '▁avail': 17671,
 '▁secular': 24381,
 '▁Opportunity': 24995,
 '▁possibly': 3673,
 'esel': 20736,
 '▁Consum': 24165,
 '▁associated': 1968,
 '▁grounds': 9808,
 '▁templates': 7405,
 'Her': 12636,
 '▁études': 17868,
 'selon': 5928,
 '▁America': 1371,
 '▁pleine': 15819,
 'beaten': 17349,
 '▁2002': 4407,
 '72': 5865,
 '▁perpetrat': 28998,
 'anchmal': 16318,
 'gler': 12683,
 '▁Sharma': 30405,
 'mitted': 16030,
 'bridge': 9818,
 'fotograf': 26515,
 '▁Console': 27513,
 '▁Suzuki': 26855,
 'or': 127,
 'fatty': 18053,
 '▁imi': 10590,
 '▁sedan': 24926,
 '▁lună': 24166,
 '▁furnace': 19808,
 '▁incur': 18663,
 '▁sentences': 16513,
 'tric': 3929,
 '▁interessiert': 23293,
 '▁Legal': 11281,
 '▁Laden': 23019,
 '▁Recycling': 28205,
 'party': 8071,
 '▁valid': 3982,
 '▁around': 300,
 '▁Ehr': 17099,
 '▁McCarthy': 30757,
 '02.': 12328,
 'ziel': 13187,
 '▁favourite': 3960,
 'fahrer': 20531,
 '▁raison': 8324,
 '▁insightful': 25621,
 'intervention': 22604,
 '▁adaug': 20852,
 '▁thrill': 22695,
 '▁Energy': 4654,
 '▁across': 640,
 'kampf': 21270,
 'optimum': 18200,
 '▁inconvenience': 25741,
 'gegeben': 6975,
 '▁stuff': 2005,
 'quickest': 31051,
 'identifying': 9690,
 '▁http': 2649,
 '▁expression': 3893,
 '▁suddenly': 8247,
 '▁politiques': 16876,
 'tiennent': 23134,
 '▁Function': 21839,
 '▁tun': 5240,
 '▁follow': 1130,
 '▁depression': 7562,
 'connected': 19386,
 '▁Philadelphia': 9511,
 'politischen': 23078,
 '▁Alzheimer': 16434,
 'state': 5540,
 '/03/': 31064,
 '▁Concord': 23478,
 'Radio': 31313,
 '▁widow': 23428,
 '▁excluded': 19678,
 'tractors': 29676,
 '▁munca': 11777,
 'ит': 22682,
 'flamm': 19381,
 'rohr': 31276,
 '▁République': 21283,
 '▁numerical': 25194,
 '▁fountain': 18051,
 '▁Reise': 6807,
 '▁opener': 19717,
 'mentioning': 27492,
 '▁ahead': 2177,
 'torilor': 10704,
 'nigsten': 31103,
 '▁£': 3996,
 '▁nor': 3701,
 '▁incidence': 20588,
 '▁redus': 16295,
 '▁campsite': 27459,
 '▁Gallery': 7557,
 'pleade': 30827,
 '▁exceptionally': 19226,
 'dem': 1778,
 '▁Kirch': 27072,
 '▁Jar': 17321,
 '▁perfectly': 3923,
 'centric': 17456,
 '▁laisser': 13783,
 '▁rounds': 14419,
 'ENE': 25576,
 '97': 4327,
 'fed': 19565,
 '▁threats': 11262,
 '▁stunt': 27572,
 '▁location': 1128,
 'iji': 17279,
 '▁affordable': 2950,
 '▁reboot': 23184,
 'producing': 30887,
 '▁peak': 6734,
 'uer': 7014,
 'jun': 6959,
 '▁Ultima': 26668,
 '▁probability': 15834,
 '▁transformation': 6586,
 '▁Devi': 24434,
 'olin': 12057,
 '▁Seiten': 8353,
 'AS': 3291,
 '▁Hin': 9515,
 '▁drives': 9350,
 '▁partially': 14610,
 '▁changer': 13412,
 '▁gegen': 2995,
 '▁cour': 11111,
 'ner': 687,
 'zam': 19271,
 '▁CBD': 12080,
 '▁whisper': 23874,
 '▁rel': 8318,
 'unforeseen': 31456,
 'ving': 3745,
 '▁Description': 7726,
 '▁Facebook': 1376,
 '▁warfare': 28229,
 '▁grease': 19373,
 '▁particle': 24317,
 '▁1/3': 23061,
 'nav': 14128,
 '▁lentil': 24026,
 'verkehr': 17105,
 '▁pub': 11943,
 '▁Eye': 9172,
 '▁introduced': 3665,
 '▁Be': 493,
 'probiert': 31450,
 '▁énergétique': 24529,
 '▁izolat': 29542,
 '▁Gold': 2540,
 'cine': 14760,
 '▁analyze': 8341,
 '▁Gor': 9826,
 'smith': 16331,
 '▁heal': 10111,
 '▁assets': 4089,
 'Expert': 29906,
 '▁Craiova': 23315,
 '▁initiatives': 6985,
 '▁Acum': 12003,
 '▁gastro': 24038,
 'paced': 18789,
 '▁Asociaţi': 29116,
 '▁success': 1269,
 '▁durata': 17920,
 '▁visualize': 25086,
 'Pol': 8931,
 '▁scan': 5924,
 '▁Interactive': 24385,
 '▁hardship': 24407,
 'enfant': 7776,
 '▁rasa': 28246,
 '▁dosage': 17166,
 'underlying': 10067,
 '▁Strecke': 20010,
 '▁started': 708,
 '▁piele': 13342,
 '▁conséquent': 27134,
 '▁neben': 7709,
 '▁decreasing': 23155,
 '▁should': 225,
 'tag': 2408,
 '▁vieții': 25845,
 '▁rising': 6937,
 '▁Internațional': 31999,
 'undergoing': 22725,
 '„': 25526,
 '4,000': 13161,
 '▁Deck': 10809,
 '▁$20': 13179,
 '▁reduce': 1428,
 '▁machinery': 13226,
 '»,': 12512,
 'ular': 4885,
 '▁reprezinta': 13947,
 'Suddenly': 28643,
 'expo': 19300,
 '▁mad': 11454,
 'ndu': 10170,
 '▁mieux': 5809,
 'unused': 23273,
 'zz': 5271,
 '▁syn': 8953,
 '▁reproduction': 19192,
 'ateurs': 12552,
 'tement': 14820,
 '▁îngrij': 24523,
 'absence': 23767,
 'EUR': 26296,
 '▁Fitzgerald': 31528,
 '▁Ideen': 14894,
 '▁declare': 15884,
 '▁Raven': 20744,
 'saving': 18265,
 '▁indispensable': 15225,
 '▁Martha': 21386,
 '▁stil': 7627,
 '▁compound': 12771,
 'deutschland': 28825,
 '▁botanical': 28560,
 '1:00': 24294,
 '▁Registration': 13571,
 '▁versch': 10020,
 'Don': 13843,
 '▁turkey': 15306,
 'hus': 11823,
 'ized': 1601,
 '▁Gewähr': 29772,
 '▁sovereign': 26800,
 '▁median': 15572,
 '▁opinion': 3474,
 'ţinut': 17697,
 'inhabited': 30732,
 '▁Thrones': 29344,
 '▁Teachers': 18991,
 '▁gagné': 31397,
 'blaze': 21020,
 'izarea': 7068,
 '▁gestalten': 19733,
 'code': 4978,
 'corporate': 25762,
 '▁2018,': 4323,
 'real': 6644,
 '▁worried': 9220,
 '▁Kindern': 14745,
 'Especially': 14232,
 '▁Noir': 21751,
 '▁Ray': 8279,
 '▁glut': 26760,
 'rutsch': 29454,
 '▁aveti': 13740,
 'trauen': 23937,
 'nch': 5457,
 '▁vous': 327,
 '▁learn': 669,
 '▁Jump': 19004,
 '▁RV': 12791,
 '▁caldura': 27603,
 '▁ça': 3664,
 '▁wichtig': 7308,
 '▁mémoire': 18245,
 '▁cortex': 29942,
 '▁bland': 28034,
 '▁transit': 11811,
 'ografie': 21693,
 'agne': 11624,
 'vii': 14553,
 '▁39': 6352,
 '▁adviser': 17013,
 'akt': 7935,
 '▁Odyssey': 29964,
 '▁funding': 3135,
 '▁after': 227,
 '▁Grow': 22132,
 'donnant': 28693,
 '▁conseillé': 30289,
 'cia': 4915,
 '▁că': 375,
 '▁occupational': 25082,
 '▁embed': 25078,
 '▁Details': 9487,
 'burn': 7223,
 'themed': 24186,
 '▁Taj': 25187,
 '▁liebe': 23803,
 'runner': 10806,
 '▁homeowners': 11634,
 '▁chacun': 9646,
 '▁view': 903,
 '▁Distance': 27370,
 '▁remarque': 26193,
 'innen': 4015,
 '▁Freude': 16230,
 '▁worden': 9775,
 '▁Peace': 11128,
 '▁charging': 10871,
 '▁stitches': 27199,
 '▁european': 14864,
 '▁donors': 16958,
 'willig': 20494,
 '▁corp': 11736,
 '▁crawl': 18639,
 '▁amplasat': 29200,
 'êt': 7425,
 '▁known': 801,
 '▁Hum': 12410,
 'plication': 13555,
 'Spezialist': 29755,
 '▁before': 274,
 '▁AAA': 22656,
 '▁Public': 2575,
 '▁Browse': 15373,
 '▁gemeinsam': 6602,
 'ică': 3546,
 'entend': 15216,
 '▁Forward': 25633,
 'Mai': 21978,
 '▁freelance': 14823,
 '▁tau': 7151,
 '▁lower': 1364,
 '▁haine': 18635,
 '▁gesichert': 31837,
 'impro': 16260,
 '▁June': 1515,
 '▁considered': 1702,
 '▁Regard': 12312,
 'nähe': 27334,
 'iker': 10109,
 '▁taie': 23054,
 '▁fou': 21114,
 '▁THE': 1853,
 'ituated': 29191,
 '▁carried': 4006,
 '▁alegeril': 23195,
 '▁Atlas': 21635,
 '▁Schmidt': 24100,
 '▁Might': 23840,
 'COM': 6657,
 '▁Clin': 22063,
 'gonna': 13366,
 '▁Therapie': 20168,
 '▁Profil': 23595,
 '▁depasi': 30502,
 '▁safeguard': 18034,
 '▁secol': 17515,
 '▁fermentation': 26064,
 '▁soleil': 15542,
 '▁28': 2059,
 'use': 1074,
 '▁shower': 2898,
 '▁remainder': 19321,
 '▁achten': 21819,
 '▁specifically': 3346,
 '▁Zur': 11688,
 'olltest': 27670,
 'Greeting': 29877,
 '▁ALL': 8229,
 'fro': 6155,
 '▁ads': 6543,
 '▁maturity': 22004,
 '▁prévention': 27175,
 '▁unlimited': 11875,
 '▁Pastor': 16365,
 'Claude': 19298,
 'rben': 10222,
 '▁maintaining': 6011,
 '▁comun': 6252,
 '▁Jamie': 17845,
 'accumul': 22274,
 '▁2020': 6503,
 '▁sponsorship': 19284,
 '▁War': 1602,
 '▁deployment': 12001,
 '▁Cha': 3643,
 '▁persistence': 29486,
 '▁Cleaning': 11115,
 '▁remboursement': 29211,
 '▁zusätzliche': 17818,
 'ONG': 15628,
 '▁developers': 5564,
 '▁mensuel': 31839,
 'carries': 11078,
 'gent': 5560,
 'Phy': 16977,
 '▁Bookmark': 10465,
 '▁intercept': 22895,
 '▁contour': 17643,
 'élection': 16166,
 '▁$40': 23853,
 'IPS': 21563,
 'schau': 8104,
 '▁names': 3056,
 '▁Zu': 1811,
 'RON': 13044,
 '▁télé': 12362,
 '▁Gill': 18584,
 '▁eingesetzt': 16336,
 '▁comunități': 30005,
 '▁4:30': 29505,
 '9)': 11728,
 'guer': 19645,
 '▁seeking': 3945,
 '▁admission': 7209,
 'ncing': 4733,
 'Unter': 25324,
 'JC': 20599,
 '▁Knight': 11595,
 'tul': 2520,
 '▁computer': 1218,
 '▁desperate': 18337,
 'kat': 8682,
 'étendue': 31833,
 '▁broadband': 19276,
 'auteur': 9474,
 '▁Flugzeug': 30702,
 '▁hair': 1268,
 '▁cetăţeni': 27922,
 '▁shall': 1522,
 'liefer': 26025,
 '▁motion': 4644,
 '▁shade': 7891,
 'platform': 29100,
 'cross': 11465,
 '▁Remove': 10002,
 '▁Writing': 10237,
 '▁shutdown': 25245,
 '▁Policy': 7587,
 '▁defined': 4802,
 '▁invest': 4032,
 'ing': 53,
 'vul': 12388,
 '▁Inspiration': 16077,
 'drafting': 26797,
 '▁Papier': 18839,
 '▁outreach': 16866,
 '▁verfüge': 23820,
 'amerikanische': 23384,
 '▁15-20': 28601,
 '▁schimbare': 18115,
 '▁Sequ': 26859,
 '<extra_id_99>': 32000,
 'lette': 15529,
 'winning': 8163,
 'progressively': 31599,
 'etched': 25872,
 'inter': 3870,
 '▁Tech': 7130,
 '▁Leading': 22798,
 'mechanical': 31564,
 'target': 24315,
 'phy': 6941,
 'midst': 12342,
 '▁Seoul': 28343,
 'mel': 2341,
 '83': 4591,
 '▁farmer': 17766,
 '▁Capital': 5826,
 '▁oven': 4836,
 '▁cycles': 15164,
 'exprim': 9813,
 '▁rustic': 14598,
 '▁uniquement': 16743,
 'goutte': 31956,
 'Combined': 28257,
 '▁hormone': 11932,
 '▁praise': 11308,
 'nehmen': 7278,
 'runde': 14483,
 '▁crise': 15093,
 '▁Pirate': 18667,
 '▁models': 2250,
 'xia': 19838,
 '▁legitimacy': 31841,
 '▁utilisateurs': 18064,
 '▁building': 740,
 'sta': 2427,
 '-4': 4278,
 '▁•': 1697,
 '▁furnizor': 21617,
 '▁adjoin': 24989,
 'stehenden': 18747,
 '▁Biology': 21211,
 '▁Gerade': 17411,
 '▁Quel': 12281,
 'се': 22036,
 'weichen': 26468,
 '▁Hoffman': 27014,
 '▁buildings': 3950,
 'fact': 8717,
 '▁hook': 7970,
 '▁Gedanken': 18952,
 '▁dezvoltat': 21718,
 'esque': 18538,
 '▁oxide': 21491,
 '▁trup': 14045,
 '▁Tips': 15356,
 "'": 31,
 '▁different': 315,
 '▁personnes': 3787,
 '▁promotional': 11074,
 '▁DUI': 23157,
 'RC': 4902,
 '▁Configur': 25306,
 '▁instituţii': 27743,
 '▁FULL': 27645,
 '▁frustr': 27020,
 '▁Plate': 14477,
 '▁towels': 19105,
 'inscrit': 17968,
 '▁tradițional': 30304,
 'determined': 22755,
 'flavored': 27877,
 '▁Jugend': 11626,
 '139': 24090,
 'utoritatea': 29922,
 'urged': 19492,
 '▁Vital': 23736,
 '▁sneakers': 27550,
 '▁Drama': 20052,
 '▁51': 11696,
 '▁Außen': 15749,
 '▁delays': 16735,
 'uddle': 25076,
 'ele': 400,
 'empre': 25569,
 '<extra_id_43>': 32056,
 'raisons': 27738,
 'Bildern': 28801,
 '▁citizenship': 22214,
 '▁Inspection': 24996,
 'applique': 16358,
 '▁mal': 1460,
 '▁lunar': 19920,
 '▁Füße': 30893,
 '▁urmeaza': 25554,
 '▁moarte': 17066,
 '▁pharmaceutical': 14106,
 '▁vers': 2676,
 'self': 7703,
 '▁recommendations': 5719,
 '▁disgust': 27635,
 'IES': 11973,
 '▁pop': 2783,
 'OFF': 15316,
 'gesehen': 11139,
 '▁jumătate': 19391,
 '▁nom': 5252,
 '▁dough': 8553,
 '▁reconstruct': 29814,
 '▁pH': 16767,
 'tex': 10354,
 '▁achievement': 10970,
 '▁zahar': 18824,
 'volu': 12740,
 'elli': 7999,
 'weist': 23368,
 '▁customers': 722,
 '▁slippery': 31071,
 '2.5': 15967,
 '▁vollständig': 18877,
 '▁measured': 8413,
 'Sollte': 15900,
 'chy': 11971,
 'rith': 30922,
 '▁device': 1407,
 '▁Scrap': 27962,
 '▁shepherd': 28743,
 '▁Basket': 26029,
 '▁compétent': 30553,
 '▁ones': 2102,
 '▁funded': 11264,
 'deutschen': 10679,
 '▁twenty': 6786,
 'HA': 5478,
 '▁panel': 2952,
 '▁gagner': 18576,
 '▁(1)': 5637,
 '▁welcoming': 12084,
 '▁toilette': 24888,
 '▁Layer': 22697,
 'schnitt': 15485,
 '▁Cur': 4116,
 'lexic': 30949,
 'itate': 1734,
 'gins': 19655,
 '▁Teams': 16651,
 '▁emoţi': 31487,
 '▁similar': 1126,
 '222': 26144,
 'ски': 30610,
 '▁2017,': 4791,
 '▁être': 1359,
 '▁anchor': 12865,
 '/04': 24288,
 '▁damaged': 6780,
 '▁merg': 12147,
 '▁iron': 3575,
 'sigură': 31470,
 '04': 6348,
 '▁counseling': 15457,
 '▁contribution': 6275,
 '▁Ford': 5222,
 'serez': 23422,
 'MIS': 28580,
 'sley': 8887,
 '▁baked': 13635,
 '▁locomotive': 31301,
 'istik': 21734,
 'statutory': 20979,
 '▁copper': 8658,
 '▁Brain': 14170,
 '▁8,': 9478,
 '▁psiho': 30125,
 '▁athlete': 17893,
 '▁continuous': 7558,
 'olar': 17401,
 '▁oyster': 26716,
 '▁kurzfristig': 30160,
 '▁sliding': 13441,
 '▁apparent': 10320,
 '▁consist': 5608,
 '▁knives': 26742,
 '▁solitude': 31274,
 '▁Southwest': 21423,
 'ectomy': 25492,
 '▁dissolve': 27157,
 '▁related': 1341,
 '▁supporters': 11172,
 '▁benefit': 1656,
 '▁impressive': 4423,
 '▁lua': 9734,
 'amba': 14303,
 '▁quantum': 21353,
 '▁melodi': 15391,
 '▁Kat': 7482,
 '▁permitted': 10548,
 'DIA': 24605,
 'concentrating': 29408,
 '▁sensitive': 6280,
 'front': 6849,
 '▁Milk': 18389,
 '▁replaced': 5821,
 '▁Mexican': 11511,
 '▁participer': 19283,
 'gelöst': 22228,
 'humain': 15279,
 '▁medicamente': 23197,
 '▁sfânt': 31645,
 '▁resistant': 11853,
 'vati': 24991,
 '▁word': 1448,
 '▁Retro': 24565,
 '▁cards': 2190,
 '▁mediu': 13120,
 'condition': 17558,
 'chèque': 29227,
 'mental': 13974,
 'tolerant': 23267,
 '▁occupation': 13792,
 '▁Transportation': 14630,
 '▁Dein': 17203,
 '▁Celtic': 21748,
 '▁Instant': 18882,
 '▁2000': 2766,
 'inscription': 14593,
 '▁cruel': 23958,
 '▁Seal': 21085,
 '▁Ceiling': 24467,
 'incarc': 14736,
 '▁Irving': 31102,
 'nonsense': 25143,
 'go': 839,
 '▁împrumut': 31534,
 '........': 19794,
 '▁illnesses': 21154,
 '▁crumbl': 22854,
 '▁fla': 5731,
 '▁conscience': 15724,
 'cyan': 27386,
 '1.0': 12734,
 '▁pine': 15178,
 'lande': 11553,
 'salv': 27074,
 '▁Scheme': 23880,
 '▁rigorous': 17577,
 '▁Geneva': 21462,
 '▁lets': 8857,
 '▁gourmet': 21300,
 'covered': 28161,
 '▁proteja': 19755,
 '▁strategic': 4519,
 '▁04': 11484,
 '▁Major': 9236,
 '▁exams': 14026,
 'aza': 5246,
 '▁giving': 1517,
 '▁giant': 6079,
 '▁Hawaiian': 24221,
 '▁noiembrie': 14470,
 'match': 19515,
 '▁circular': 15646,
 '▁realized': 5723,
 '▁motor': 2340,
 '▁nec': 9705,
 '▁Abstract': 20114,
 '▁Materialien': 20636,
 '▁Who': 2645,
 '▁suppliers': 6603,
 '▁seizures': 30406,
 'ни': 14391,
 'destin': 13557,
 '▁revien': 21109,
 'schaden': 30939,
 '▁kürz': 23796,
 '▁thought': 816,
 '▁goût': 14336,
 '▁nicht': 311,
 '▁Reflect': 23966,
 '▁Other': 2502,
 'injected': 26854,
 '▁funds': 2731,
 'ki': 2168,
 '▁life': 280,
 '▁semantic': 27632,
 'Severin': 30814,
 'abi': 15975,
 '▁position': 1102,
 '▁upgrading': 21066,
 '▁rev': 5109,
 '▁half': 985,
 '▁viata': 5966,
 'proclaimed': 28901,
 '▁technology': 748,
 '▁calorii': 31655,
 'bird': 9414,
 'verschiedenen': 7811,
 '▁encourage': 2454,
 '▁GRA': 23194,
 '▁someone': 841,
 '▁oppos': 10720,
 '▁Koch': 16608,
 '▁campus': 4730,
 '▁Deluxe': 23355,
 'rushed': 18731,
 '▁lors': 4692,
 'positive': 26093,
 'restoring': 22938,
 '▁apart': 3943,
 '▁iubire': 18572,
 '▁Loch': 24922,
 '▁electric': 2806,
 '▁forest': 5827,
 'fuel': 21692,
 'ator': 1016,
 '▁version': 988,
 '▁veche': 24126,
 '▁simpla': 24846,
 '▁trauma': 11105,
 '▁Handwerk': 25783,
 '▁massage': 6967,
 '▁parcare': 26194,
 '▁glyco': 27170,
 '▁anonym': 19581,
 'appli': 27515,
 '▁komplett': 10766,
 '▁Again': 7204,
 '▁Minuten': 8314,
 '▁Joyce': 27121,
 '▁spannend': 15770,
 '66': 3539,
 '▁rocks': 12288,
 '▁compiler': 29801,
 '▁significance': 11978,
 'seated': 22933,
 '▁galben': 21461,
 'also': 13208,
 '▁spider': 18612,
 'crest': 21443,
 'weiterhin': 16694,
 '▁Kuchen': 28655,
 '▁Seat': 15915,
 '▁unsafe': 26435,
 '▁siège': 21442,
 '▁bleu': 15197,
 'dulci': 26227,
 '-10': 4536,
 '▁Producer': 25348,
 '▁Vector': 29011,
 '▁malicious': 22326,
 'deciding': 12053,
 '▁doors': 3377,
 '▁Ya': 4701,
 '▁Spectrum': 29998,
 '▁blieb': 26555,
 'ization': 1707,
 '▁Bomb': 16327,
 '▁Only': 3462,
 '▁residual': 27687,
 '<extra_id_3>': 32096,
 'igte': 28364,
 'turned': 24346,
 'cino': 21919,
 'wSt': 29591,
 '▁asteapta': 30592,
 '▁trilogy': 29093,
 '▁believe': 857,
 '▁intense': 6258,
 '▁Blvd': 24241,
 '▁zurück': 4204,
 '▁toast': 16544,
 '▁agency': 3193,
 'GU': 13961,
 '▁camp': 2856,
 'ITA': 21524,
 '▁wings': 13943,
 '▁ianuarie': 12883,
 '▁eigene': 7367,
 '▁specify': 11610,
 '▁overnight': 8521,
 '▁Harley': 26085,
 '▁war': 615,
 '▁ajutorul': 10082,
 '▁Page': 5545,
 'J': 683,
 'oversized': 24698,
 '▁artwork': 7924,
 '<extra_id_53>': 32046,
 'phi': 11692,
 'Magazin': 24773,
 'Jacques': 17453,
 '▁machen': 3123,
 '▁Rehabilitation': 26779,
 'WOOD': 29637,
 '▁Pizza': 15365,
 'chon': 17128,
 '▁distrus': 26246,
 '▁café': 11949,
 '▁incident': 5415,
 '▁Financial': 5421,
 '▁Ensemble': 23481,
 '▁wager': 21787,
 '▁discourage': 20191,
 '▁shoulder': 8173,
 'extending': 16878,
 'AIR': 18375,
 '▁Sorry': 11342,
 '▁Apartament': 31630,
 'effi': 23473,
 'rait': 6893,
 '▁Keep': 3521,
 '▁Polizei': 16483,
 '▁surrender': 23970,
 '▁whatsoever': 19842,
 '▁archive': 13269,
 'ange': 3280,
 '6-7': 25302,
 '▁Constantin': 15838,
 '62': 4056,
 '▁broad': 4358,
 '▁plans': 1390,
 '▁Trail': 8939,
 '▁wives': 28908,
 ...}

In [17]:
len(Vs)

32100

In [18]:
hindi_vocab=set()

for tokenized_hindi_sent in data["DstSent"]:
    hindi_vocab.update(tokenized_hindi_sent)

In [19]:
hindi_vocab

{'आखिरकार',
 'ड्राइवर',
 'अपनी',
 'धोने',
 'कांतिमान',
 'मोरक्को',
 'दूसरा',
 'मोन्टकाम',
 'योनि',
 'उड़ाओ',
 'हूँगा',
 'पत्रों',
 'नरक',
 'बोर',
 'खोदना',
 'आनन्द',
 'इससे',
 'अभिमानी',
 'आगन्तुकों',
 'छाया',
 'मोहल्ले',
 'महंगा',
 'तौलिये',
 'स्कीर',
 'भौतिक',
 'बार',
 'जीवन',
 'सेनापति',
 'उम्मीदों',
 'खत',
 'ब्रिटिश',
 'अभिनेता',
 'इन्हें',
 'जापानीयों',
 'नक्षत्रों',
 'चाँटे',
 'गिरजाघर',
 'कपड़ों',
 'सुलाना',
 'सका',
 'गुम',
 'गवाह',
 'उठाइये',
 'गाते',
 'मूँह',
 'मैंनें',
 'मीटर',
 'गुलदान',
 'हाथों',
 'फादिल',
 'परोसा',
 'चलन',
 'पती',
 'बौद्ध',
 'लडकी',
 'दिखता',
 'घायलो',
 'बारबार',
 'शीतयुद्ध',
 'बताएँ',
 'रोमन',
 'आओ',
 'नीदरलैंड',
 'जंग',
 'बजाती',
 'जलेगा',
 'थक',
 'धैर्य',
 'अनाथ',
 'गोश्त',
 'सिंगापुर',
 'आसन',
 'फोटो',
 'कॅलिफॉर्निया',
 'कहूँगी',
 '"',
 'पंडित',
 'नींव',
 'दाँतों',
 'दफ़तर',
 'कीड़ों',
 'अल्जेरियन',
 'फ़ोटोकॉपियर',
 'बराबरी',
 'नव',
 'हिरोको',
 'जापानी',
 'मशरूम',
 'ड्राईवर',
 'स्क्रैच',
 'मकड़ियों',
 'कुवैत',
 'टकराई',
 'बोओगे',
 'दुस्साहस',
 'सुलेमान',
 'नानीजी',
 'मारिको',
 'बांटती',
 'तिनके',
 'इछुक',
 'प्रभावित',
 'रुकूँगी',
 'सौंदरराजन',
 'रोग',
 'बाताऊँगी',
 'पढ़ाई',
 'ढक',
 'अफगानिस्तान',
 'कागज़ी',
 'धीरे',
 'पूछा',
 'अंगूर',
 'ज़रूरत',
 'शब्दों',
 'नृत्य',
 'बिखेर',
 'कुछ',
 'श्रिमान',
 'नहिं',
 'बसने',
 'गद्दारी',
 'लिंकनने',
 'झुकी',
 'उन्मूलन',
 'दबाकर',
 'अश्लीलता',
 'संक्षिप्त',
 'नाई',
 'मूंद',
 'नहा',
 'मछलीयां',
 'नाइट',
 'विदोश',
 'विकल्पों',
 'ढका',
 'मचाते',
 'चिल्लाना',
 'ऊँचा',
 'ये',
 'धोए',
 'रात',
 'कपडों',
 'ततैयां',
 'सस्ते',
 'करदें',
 'पूजा',
 'मोटा',
 'काग़ज़',
 'हील्स',
 'ओलंपिक',
 'दुरुपयोग',
 'परिश्रम',
 'स्वतंत्र',
 'श्रम',
 'सिक्का',
 'होते',
 'अवार्ड',
 'पड',
 'अंधों',
 'नानी',
 'धरती',
 'मील',
 'लाऊँगा',
 'किया',
 'सीखनी',
 'निकलो',
 'होल्ड',
 'आफ़्रिका',
 'उगेगा',
 'आकाश',
 'भाषाएँ',
 'पूछ',
 'मानती',
 'कमी',
 'ईंधनों',
 'वाइन',
 'रुकें',
 'म्यूरियल',
 'भाईसाहब',
 'हीरो',
 'सिपाही',
 'इजाज़त',
 'कर्मचारी',
 'अकल',
 'सुनती',
 'लिफ़ाफ़े',
 'विपत्ती',
 'संगमरमर',
 'बिल्लियाँ',
 'बढ़ी',
 'बूढ़ी',
 'फाइल',
 'दिलाई',
 'ट्राए',
 'जाचुका',
 'पौधों',
 'मॉडल',
 'विद्रोह',
 'किम',
 'हंस',
 'हकों',
 'रहीं',
 'होठ',
 'फुसफुसाकर',
 'पहुँचे',
 'गुना',
 'संदेश',
 'सम्पर्क',
 'मरम्मत',
 'रुकते',
 'शाँत',
 'टाम',
 'बेचारा',
 'कम',
 'चादरें',
 'फ़र्नीचर',
 'बह',
 'ट्रम्पेट',
 'बिछाई',
 'समझते',
 'पुरे',
 'निकाली',
 'सोवियेत',
 'लिस्बन',
 'सातवाँ',
 'चाकलेट',
 'टहलें',
 'श्रीलंका',
 'गाओ',
 'माँगा',
 'द',
 'पैग़ाम',
 'कॉफ़ी',
 'पहुँचाया',
 'थूकेगा',
 'घंटे',
 'कौआ',
 'पोंछो',
 'क्षण',
 'कबूतर',
 'बैठने',
 'घास',
 'विध्यार्थी',
 'ß',
 'सिखाए',
 'ऑफ़',
 'स्थापित',
 'दिखाता',
 'छुएँ',
 'गोली',
 'कीचड़',
 'इस्त्री',
 'इराक़',
 'काटकर',
 'चावी',
 'सही',
 'सितंबर',
 'ज़माने',
 'थामने',
 'केन',
 'नर्म',
 'लिपटा',
 'नाम',
 'रहा',
 'स्थित',
 'जाएं',
 'चपटी',
 'बाघ',
 'नियंत्रित',
 'ऐक्टिनियम',
 '०००',
 'खेद',
 'पीया',
 'सिक्कों',
 'ज़मीर',
 'सवार',
 'मुझमें',
 'आवाज़',
 'सकता',
 'आपका',
 'मलाई',
 'आइए',
 'सीता',
 'मुताबिक',
 'अकेलापन',
 'साम्राज्य',
 'पर',
 'लाईं',
 'किसान',
 'गोलियों',
 'मिनटों',
 'डालर',
 'ब्लॉगर',
 'सीधे',
 'वीरान',
 'कायदे',
 'दूँगी',
 'करदो',
 'बहिष्कार',
 'अभी',
 'कार्यकर्म',
 'कमाता',
 'पैरों',
 'खींच',
 'सेइचो',
 'उच्चारण',
 'बनातीं',
 'माँगे',
 'अच्छाई',
 'कछुए',
 'दिखा',
 'ऊटपटाँग',
 'सोकर',
 'बारी',
 'खोलूँ',
 'लॅपटॉप',
 'हंसो',
 'बाएँ',
 'तालियां',
 'युवा',
 'नौ',
 'डरपोक',
 'गायिका',
 'रेखा',
 'पनाह',
 'कार्यालय',
 'घायल',
 'सटिया',
 'भुला',
 'आते',
 'डायरी',
 'चुकीं',
 'बॉस्टन',
 'बाप',
 'येरुशलयिम',
 'ख़रीदी',
 'शक',
 'पढ़नी',
 'प्रशंसक',
 'चुनने',
 'दिखाईए',
 'इस',
 'उपहार',
 'इच्छानुसार',
 'ईश्वर',
 'उबले',
 'आइंस्टीन',
 'समझोगी',
 'सिखाई',
 'रुकिए',
 'धर्माधिकरण',
 'बताएं',
 'बताइये',
 'शुभकामानाएँ',
 'परिचित',
 'मिलिए',
 'लापता',
 'पाँचवे',
 'बृहस्पति',
 'कोमा',
 'किसको',
 'ग़ुस्से',
 'मारे',
 'बयान',
 'तुमने',
 'सालगिरह',
 'लेती',
 'जूतों',
 'क्र',
 'गोलार्धों',
 'समुंदर',
 'लिखो',
 'ट्रेफ़िक',
 'टौम',
 'समझ',
 'जाए',
 'A',
 'तारे',
 '१९९६',
 'चीज़ें',
 'करते',
 'लेआऊँ',
 'जियामिंग',
 'श्वार्झनेगर',
 'सर',
 'ट्रोल',
 'शराब',
 'प्रदर्शन',
 'प्रकट',
 'रहना',
 'गेंदबाज़ी',
 'आपको',
 'सब',
 'स्विमसूट',
 'स्थानिक',
 'विश्वयुद्ध',
 'बाली',
 'मौत',
 'रिहाई',
 'दम',
 'हमें',
 'हँसाना',
 'कॉन्सर्ट',
 'बैटमैन',
 'दोनों',
 'मिलीं',
 'तादाशी',
 'चाहें',
 'बीमारों',
 'वर्षा',
 'लिखे',
 'अल',
 'आर्थर',
 'निर्दयी',
 'बांधी',
 'जज्बे',
 'शोक',
 'दाढ़ी',
 'हकला',
 'लेखकों',
 'पूछूं',
 'कासिम',
 'सतत',
 'भरेगा',
 'परिस्तिथियों',
 'पेट',
 'क्रोध',
 'मशहूर',
 'यामादा',
 'स्वीकारेगा',
 'पहेली',
 'पंद्रहवीं',
 'उत्पाद',
 'फेंकने',
 'पाँव',
 'राजधानीयां',
 'स्थल',
 'हर',
 'टीम',
 'अनहोनी',
 'वो',
 'करदिआ',
 'हैसियत',
 'चश्मा',
 'कामकाज',
 'टाई',
 '७५',
 'बिताई',
 'रहोगे',
 'बर्ट',
 'खिल',
 'वार',
 'समझेंगे',
 'कन्नड़',
 'हवाई',
 'कविताएँ',
 'भाग्य',
 'देशी',
 'रिफ्रेश',
 'फारसी',
 'जँचती',
 'पत्नी',
 'फ़िदा',
 'सहयोग',
 'लौडा',
 'छिप',
 'पिकाचु',
 'बलों',
 'मेड्रिड',
 'बुरगुंदीयाई',
 'रोज',
 'जांच',
 'गाल',
 'चूम',
 'डराती',
 'शत्रु',
 'बजाते',
 'बदबू',
 'टी',
 'खर्चना',
 'संदेस',
 'बचाने',
 'स्मिथ',
 'पट्टियाँ',
 'विमान',
 'बढ़ो',
 'दल',
 'अनुवाद',
 'ब्रेड',
 'ईसप',
 'गे',
 'घूर',
 'स्थान',
 'सवेरे',
 'चुप',
 'ऑस्ट्रेल्या',
 'धीमे',
 'ओपन',
 'रेस',
 'बुद्धी',
 'रेपुबलिका',
 'भेजो',
 'इनका',
 'मॉली',
 'बोलनी',
 'आटा',
 'पोतियां',
 'मेहमान',
 'रिओ',
 'लागु',
 'मंगाऊँ',
 'थप्पड़',
 'बैठा',
 'डराने',
 'गप',
 'कोरिया',
 'कृप्या',
 'आमंत्रण',
 'निकला',
 'गुलाब',
 'युल',
 'जाएगी',
 'प्रधानमंत्री',
 'बुद्ध',
 'उबासी',
 'देखा',
 'साँस',
 'ज़िन्दाबाद',
 'युक्रेनी',
 'दुश्मनों',
 'पैक',
 'प्रकार',
 'टिकिट',
 'हालचाल',
 'भौंका',
 'रवि',
 'चाहूंगी',
 'राजाओं',
 'प्रेमी',
 'दूधवाला',
 'बेहद',
 'बताउँगी',
 'महाराष्ट्र',
 'दादीजी',
 'चट्टान',
 'सहनशीलता',
 'मोबी',
 'बुरा',
 'बाताऊँगा',
 'पार्श्व',
 'आसान',
 'मसीह',
 'बेआराम',
 'लेकिन',
 'संन्यास',
 'जनतंत्र',
 'किला',
 'रोना',
 'बाय',
 'आकछू',
 'लक्सेमबोर्ग',
 'अच्छा',
 'बुला',
 'बोतलों',
 'ताईवान',
 'गेट',
 'अधिक',
 'जोख़िम',
 'लिखना',
 'भाग्यशाली',
 'अखबारों',
 'पास',
 'अटक',
 'वाद्य',
 'मिनिटों',
 'गरीब',
 'घनिष्ठ',
 'रोमैंटिक',
 'ग्रह',
 'पाती',
 'खान',
 'अंगूठी',
 'तेज़',
 'ग़लतियों',
 'जानि',
 'अल्जीरिया',
 'जटिल',
 'वॉरेन',
 'ऋगवेद',
 'स्वयं',
 'देस',
 'गैस',
 'पिकचर',
 'सुधारिए',
 'कबाब',
 'जिसमें',
 'सिगार',
 'तोदाइजी',
 'क्योतो',
 'घुमा',
 'बुलाई',
 'जीती',
 'नारियल',
 'समस्याएं',
 'झुकाएं',
 'थी',
 'बरसी',
 'पुआ',
 'प्रसिद्ध',
 'गैरेज',
 'ख़ज़ाना',
 'कौशल',
 'उच्चार',
 'चित',
 'शांत',
 'बंद',
 'मंदिरों',
 'शिकार',
 'पैसेवाला',
 'सेक्स',
 'बैठो',
 'अंधेरा',
 'किसलिए',
 'पुताई',
 'वफादार',
 'घुसाओ',
 'पाया',
 'मनाते',
 'बतादूँगा',
 'किन्तु',
 'अक्साई',
 'ढूँढना',
 'त्यागपत्र',
 'निकालें',
 'जॉगिंग',
 'सुपर',
 'घटिया',
 'बाल',
 'लुंड',
 'पकाना',
 'सूखा',
 'बीमार',
 'इनमें',
 'पकाएं',
 'जैक',
 'खूनी',
 'गयीं',
 'खिलाफ़',
 'चंगेज़',
 'प्रदेशों',
 'थम',
 'पोस',
 'पूँछ',
 'टाइप',
 'इन्सान',
 'मनवा',
 'बगुले',
 'लेलिया',
 'चाहता',
 'शर्मीली',
 'विपत्तिजनक',
 'हस्ताक्षर',
 'पुल',
 'ऊँचाई',
 'छूट',
 'अनपेक्षित',
 'मज़ाक',
 'छत्तीसगढ़',
 'कॉपीराईट',
 'टिकती',
 'फ़्रैंकफुर्ट',
 'शिफ़्ट',
 'रंडी',
 'आपत्ति',
 'क्योटो',
 'अमरीका',
 'गिरनी',
 'झूठा',
 'किलोमीटर',
 'बीजों',
 'भ्रष्टाचार',
 'जोर',
 'अलविदा',
 'लिखतें',
 'अधिकांश',
 'दौड़ने',
 'रह',
 'पोषण',
 'ज़बरदस्ती',
 'ई',
 'चीज़ों',
 'कड़वा',
 'हस्तमैथुन',
 'टेट्रिस',
 'कैफ़े',
 'कूदते',
 'ताओ',
 'समझता',
 'ध्वज',
 'नियंत्रण',
 'स्नातक',
 'चाहेगा',
 'जीतता',
 'ख़ाली',
 'स्वादिष्ट',
 'करोगे',
 'तेलंगना',
 'भागी',
 'अरेंज',
 'वादी',
 'छटी',
 'लोकप्रिय',
 'अज्ञान',
 'अटका',
 '९',
 'नज़रअंदाज़',
 '(',
 'ठहराया',
 'जानतीं',
 'टेरा',
 'प्रेमपूर्वक',
 'मुझे',
 'यूरोप',
 'लौटकर',
 'कड़ी',
 'होनी',
 'हुकूमत',
 'पेशवा',
 'सिखाती',
 'व्यक्ती',
 'कबसे',
 'केंद्र',
 'पाते',
 'बनो',
 'न्योता',
 'सुनी',
 'तरफ़',
 'बच्चों',
 'चूमने',
 'चालू',
 'मर',
 'ज़हरीली',
 'ज़िरी',
 'कमाल',
 'भौंह',
 'लूंगी',
 'मकान',
 'आसमान',
 'मॉर्ड्रेड',
 'मुच',
 'परमेश्वर',
 'आई',
 'फर्क',
 'डालने',
 'क्षेत्र',
 'सेवाओं',
 'सेव',
 'अकेले',
 'घना',
 'सावधान',
 'ढल',
 'शा',
 'बदलता',
 'शान्ति',
 'दूंगी',
 'ख़ून',
 'लालच',
 'चक्कर',
 '|',
 'करती',
 'मुफ़्त',
 'शुक्रवार',
 'मज़े',
 'डाक',
 'भूखा',
 'वेलेंटाइन',
 'कक्ष',
 'अपनाएं',
 'बनवानी',
 'महँगी',
 'सफ़ल',
 'आख़िरकार',
 'मिलें',
 'सँभाला',
 'मर्ज़ी',
 'ड्रैगन्स',
 'नाक',
 'कुचल',
 'भाषाओं',
 'जमे',
 'होनेवाली',
 'पहाड़ियां',
 'पेड़',
 'सिरों',
 'चुम्मा',
 'बिस्टर',
 'जीकर',
 'लत',
 'क्लास',
 'बंदा',
 'इब्रानी',
 'सँकरी',
 'हठी',
 'अंग्रेज़ी',
 'नील',
 'मारती',
 'रुको',
 'इलाक़ा',
 'कलकत्ता',
 'एंड',
 'बाज़ी',
 'कहूँगा',
 'हिस्सा',
 'रेखाएं',
 'श्रेष्ठ',
 'अलग',
 'तैयारी',
 'जोड़ा',
 'बेबी',
 'चरित्र',
 'परिणाम',
 'सिखाएंगे',
 'आदतें',
 'सुरियाह',
 'दुनिया',
 'कहूं',
 'मोटे',
 'गठरी',
 'साइट',
 'तरफ',
 'तोहफ़ा',
 'पट',
 'बीजिंग',
 'स्वाधीनता',
 'देंगे',
 'विक्टोरिया',
 'दोस्ती',
 'जनसंख्या',
 'मारीओ',
 'बैट',
 'बेसब्री',
 'ज़ोरों',
 'काट',
 'हुएं',
 'सूक',
 'लगने',
 'मंगवाया',
 'टैक्स',
 'विरुद्ध',
 'पूर्वाभास',
 'दहातु',
 'बाढ़',
 'बल्कि',
 'निकम्मा',
 'ज़ेल्डा',
 'मुड़ता',
 'हिसाशी',
 'परस्पर',
 'उत्पादों',
 'गायकों',
 'निकल',
 'कैंडी',
 'पड़ें',
 'लेने',
 'अगले',
 'विशेष',
 'प्रतियोगिता',
 'पूछोगे',
 'वॉरक्राफ्ट',
 'मोहन',
 'कथाओं',
 'आक्रमण',
 'सेहत',
 'नंगे',
 'नसीब',
 'बैठते',
 'हल्का',
 'मे॑',
 'तय',
 'जिससे',
 'बोलतीं',
 'सुपरमैन',
 'अंदेखा',
 'न्यूयॉर्क',
 'दफ़नाया',
 'नगरी',
 'ज़िम्मेदार',
 'खेलतीं',
 '20',
 'इंटरव्यू',
 'चाहेंगी',
 'पायी',
 'वायोला',
 'पुस्तक',
 'पढ़ते',
 'सता',
 'अपने',
 'मारो',
 'लौटें',
 'पियो',
 'जीतने',
 'इंतजार',
 'आँत्वाँ',
 '१८६५',
 'भूतों',
 'कुर्सी',
 'इन्टरनेट',
 'जीव',
 'हित',
 'पढ़ता',
 'ज़हीरुद्दीन',
 'सहायता',
 'केनडी',
 'लगाए',
 'विवाह',
 'असभ्यता',
 'भूख',
 'थका',
 'इसीलिए',
 'मच्छरों',
 'उठाइए',
 'उन्होनें',
 'जानवरों',
 'अध्यापक',
 'रोमानी',
 'बसीं',
 'विच्छेद',
 'नर्क',
 'जिराफ़',
 'कैरन',
 'ऐलान',
 'एकता',
 'जितना',
 'औरडर',
 'तोड़ी',
 'पीकर',
 'परेशानी',
 'चाहूँगा',
 'शरम',
 'मिथुन',
 'मिलेंगीं',
 'भय्या',
 'धोना',
 'बोलते',
 'पालतू',
 'लगेगा',
 'एस्पान्या',
 'तलना',
 'फ़ायदा',
 'खिंचा',
 'शनिवार',
 '१९७४',
 'गायब',
 'रहकर',
 'अड़ियल',
 'उतना',
 'अफ्रीका',
 'मिल',
 'कुशलतापूर्वक',
 'चलाते',
 'होगा',
 'खुली',
 'गै',
 'जाउँगा',
 'प्रतिस्पर्धा',
 'चूहें',
 'पॉलिना',
 'हायाकावा',
 'तेहरान',
 'लिखी',
 'लाती',
 'पहना',
 'मेल',
 'पहन',
 'हीरा',
 'जाऊंगा',
 'ज़ीलंड',
 'शरदोत्सव',
 'मदर',
 'गेंदबाज',
 'देखते',
 'विटामिन',
 'हेनरी',
 'org',
 'देना',
 'छोड़े',
 'मुसलमान',
 'बदलाव',
 'पवित्र',
 'चलें',
 'सिखा',
 'दास',
 'इच्छुक',
 'स्वार्थी',
 'विजेता',
 'सिखाओगी',
 'गति',
 'मुक्त',
 'टेक्सी',
 ...}

In [20]:
len(hindi_vocab)

7069

In [21]:
Vd=dict()
for idx, token in enumerate(hindi_vocab):
    Vd[token]=idx+3
Vd["<PAD>"]=0
Vd["<SOS>"]=1
Vd["<EOS>"]=2

In [22]:
Vd

{'आखिरकार': 3,
 'ड्राइवर': 4,
 'अपनी': 5,
 'धोने': 6,
 'कांतिमान': 7,
 'मोरक्को': 8,
 'दूसरा': 9,
 'मोन्टकाम': 10,
 'योनि': 11,
 'उड़ाओ': 12,
 'हूँगा': 13,
 'पत्रों': 14,
 'नरक': 15,
 'बोर': 16,
 'खोदना': 17,
 'आनन्द': 18,
 'इससे': 19,
 'अभिमानी': 20,
 'आगन्तुकों': 21,
 'छाया': 22,
 'मोहल्ले': 23,
 'महंगा': 24,
 'तौलिये': 25,
 'स्कीर': 26,
 'भौतिक': 27,
 'बार': 28,
 'जीवन': 29,
 'सेनापति': 30,
 'उम्मीदों': 31,
 'खत': 32,
 'ब्रिटिश': 33,
 'अभिनेता': 34,
 'इन्हें': 35,
 'जापानीयों': 36,
 'नक्षत्रों': 37,
 'चाँटे': 38,
 'गिरजाघर': 39,
 'कपड़ों': 40,
 'सुलाना': 41,
 'सका': 42,
 'गुम': 43,
 'गवाह': 44,
 'उठाइये': 45,
 'गाते': 46,
 'मूँह': 47,
 'मैंनें': 48,
 'मीटर': 49,
 'गुलदान': 50,
 'हाथों': 51,
 'फादिल': 52,
 'परोसा': 53,
 'चलन': 54,
 'पती': 55,
 'बौद्ध': 56,
 'लडकी': 57,
 'दिखता': 58,
 'घायलो': 59,
 'बारबार': 60,
 'शीतयुद्ध': 61,
 'बताएँ': 62,
 'रोमन': 63,
 'आओ': 64,
 'नीदरलैंड': 65,
 'जंग': 66,
 'बजाती': 67,
 'जलेगा': 68,
 'थक': 69,
 'धैर्य': 70,
 'अनाथ': 71,
 'गोश्त': 72,
 'सिंगापुर': 73,
 'आसन': 74,
 'फोटो': 75,
 'कॅलिफॉर्निया': 76,
 'कहूँगी': 77,
 '"': 78,
 'पंडित': 79,
 'नींव': 80,
 'दाँतों': 81,
 'दफ़तर': 82,
 'कीड़ों': 83,
 'अल्जेरियन': 84,
 'फ़ोटोकॉपियर': 85,
 'बराबरी': 86,
 'नव': 87,
 'हिरोको': 88,
 'जापानी': 89,
 'मशरूम': 90,
 'ड्राईवर': 91,
 'स्क्रैच': 92,
 'मकड़ियों': 93,
 'कुवैत': 94,
 'टकराई': 95,
 'बोओगे': 96,
 'दुस्साहस': 97,
 'सुलेमान': 98,
 'नानीजी': 99,
 'मारिको': 100,
 'बांटती': 101,
 'तिनके': 102,
 'इछुक': 103,
 'प्रभावित': 104,
 'रुकूँगी': 105,
 'सौंदरराजन': 106,
 'रोग': 107,
 'बाताऊँगी': 108,
 'पढ़ाई': 109,
 'ढक': 110,
 'अफगानिस्तान': 111,
 'कागज़ी': 112,
 'धीरे': 113,
 'पूछा': 114,
 'अंगूर': 115,
 'ज़रूरत': 116,
 'शब्दों': 117,
 'नृत्य': 118,
 'बिखेर': 119,
 'कुछ': 120,
 'श्रिमान': 121,
 'नहिं': 122,
 'बसने': 123,
 'गद्दारी': 124,
 'लिंकनने': 125,
 'झुकी': 126,
 'उन्मूलन': 127,
 'दबाकर': 128,
 'अश्लीलता': 129,
 'संक्षिप्त': 130,
 'नाई': 131,
 'मूंद': 132,
 'नहा': 133,
 'मछलीयां': 134,
 'नाइट': 135,
 'विदोश': 136,
 'विकल्पों': 137,
 'ढका': 138,
 'मचाते': 139,
 'चिल्लाना': 140,
 'ऊँचा': 141,
 'ये': 142,
 'धोए': 143,
 'रात': 144,
 'कपडों': 145,
 'ततैयां': 146,
 'सस्ते': 147,
 'करदें': 148,
 'पूजा': 149,
 'मोटा': 150,
 'काग़ज़': 151,
 'हील्स': 152,
 'ओलंपिक': 153,
 'दुरुपयोग': 154,
 'परिश्रम': 155,
 'स्वतंत्र': 156,
 'श्रम': 157,
 'सिक्का': 158,
 'होते': 159,
 'अवार्ड': 160,
 'पड': 161,
 'अंधों': 162,
 'नानी': 163,
 'धरती': 164,
 'मील': 165,
 'लाऊँगा': 166,
 'किया': 167,
 'सीखनी': 168,
 'निकलो': 169,
 'होल्ड': 170,
 'आफ़्रिका': 171,
 'उगेगा': 172,
 'आकाश': 173,
 'भाषाएँ': 174,
 'पूछ': 175,
 'मानती': 176,
 'कमी': 177,
 'ईंधनों': 178,
 'वाइन': 179,
 'रुकें': 180,
 'म्यूरियल': 181,
 'भाईसाहब': 182,
 'हीरो': 183,
 'सिपाही': 184,
 'इजाज़त': 185,
 'कर्मचारी': 186,
 'अकल': 187,
 'सुनती': 188,
 'लिफ़ाफ़े': 189,
 'विपत्ती': 190,
 'संगमरमर': 191,
 'बिल्लियाँ': 192,
 'बढ़ी': 193,
 'बूढ़ी': 194,
 'फाइल': 195,
 'दिलाई': 196,
 'ट्राए': 197,
 'जाचुका': 198,
 'पौधों': 199,
 'मॉडल': 200,
 'विद्रोह': 201,
 'किम': 202,
 'हंस': 203,
 'हकों': 204,
 'रहीं': 205,
 'होठ': 206,
 'फुसफुसाकर': 207,
 'पहुँचे': 208,
 'गुना': 209,
 'संदेश': 210,
 'सम्पर्क': 211,
 'मरम्मत': 212,
 'रुकते': 213,
 'शाँत': 214,
 'टाम': 215,
 'बेचारा': 216,
 'कम': 217,
 'चादरें': 218,
 'फ़र्नीचर': 219,
 'बह': 220,
 'ट्रम्पेट': 221,
 'बिछाई': 222,
 'समझते': 223,
 'पुरे': 224,
 'निकाली': 225,
 'सोवियेत': 226,
 'लिस्बन': 227,
 'सातवाँ': 228,
 'चाकलेट': 229,
 'टहलें': 230,
 'श्रीलंका': 231,
 'गाओ': 232,
 'माँगा': 233,
 'द': 234,
 'पैग़ाम': 235,
 'कॉफ़ी': 236,
 'पहुँचाया': 237,
 'थूकेगा': 238,
 'घंटे': 239,
 'कौआ': 240,
 'पोंछो': 241,
 'क्षण': 242,
 'कबूतर': 243,
 'बैठने': 244,
 'घास': 245,
 'विध्यार्थी': 246,
 'ß': 247,
 'सिखाए': 248,
 'ऑफ़': 249,
 'स्थापित': 250,
 'दिखाता': 251,
 'छुएँ': 252,
 'गोली': 253,
 'कीचड़': 254,
 'इस्त्री': 255,
 'इराक़': 256,
 'काटकर': 257,
 'चावी': 258,
 'सही': 259,
 'सितंबर': 260,
 'ज़माने': 261,
 'थामने': 262,
 'केन': 263,
 'नर्म': 264,
 'लिपटा': 265,
 'नाम': 266,
 'रहा': 267,
 'स्थित': 268,
 'जाएं': 269,
 'चपटी': 270,
 'बाघ': 271,
 'नियंत्रित': 272,
 'ऐक्टिनियम': 273,
 '०००': 274,
 'खेद': 275,
 'पीया': 276,
 'सिक्कों': 277,
 'ज़मीर': 278,
 'सवार': 279,
 'मुझमें': 280,
 'आवाज़': 281,
 'सकता': 282,
 'आपका': 283,
 'मलाई': 284,
 'आइए': 285,
 'सीता': 286,
 'मुताबिक': 287,
 'अकेलापन': 288,
 'साम्राज्य': 289,
 'पर': 290,
 'लाईं': 291,
 'किसान': 292,
 'गोलियों': 293,
 'मिनटों': 294,
 'डालर': 295,
 'ब्लॉगर': 296,
 'सीधे': 297,
 'वीरान': 298,
 'कायदे': 299,
 'दूँगी': 300,
 'करदो': 301,
 'बहिष्कार': 302,
 'अभी': 303,
 'कार्यकर्म': 304,
 'कमाता': 305,
 'पैरों': 306,
 'खींच': 307,
 'सेइचो': 308,
 'उच्चारण': 309,
 'बनातीं': 310,
 'माँगे': 311,
 'अच्छाई': 312,
 'कछुए': 313,
 'दिखा': 314,
 'ऊटपटाँग': 315,
 'सोकर': 316,
 'बारी': 317,
 'खोलूँ': 318,
 'लॅपटॉप': 319,
 'हंसो': 320,
 'बाएँ': 321,
 'तालियां': 322,
 'युवा': 323,
 'नौ': 324,
 'डरपोक': 325,
 'गायिका': 326,
 'रेखा': 327,
 'पनाह': 328,
 'कार्यालय': 329,
 'घायल': 330,
 'सटिया': 331,
 'भुला': 332,
 'आते': 333,
 'डायरी': 334,
 'चुकीं': 335,
 'बॉस्टन': 336,
 'बाप': 337,
 'येरुशलयिम': 338,
 'ख़रीदी': 339,
 'शक': 340,
 'पढ़नी': 341,
 'प्रशंसक': 342,
 'चुनने': 343,
 'दिखाईए': 344,
 'इस': 345,
 'उपहार': 346,
 'इच्छानुसार': 347,
 'ईश्वर': 348,
 'उबले': 349,
 'आइंस्टीन': 350,
 'समझोगी': 351,
 'सिखाई': 352,
 'रुकिए': 353,
 'धर्माधिकरण': 354,
 'बताएं': 355,
 'बताइये': 356,
 'शुभकामानाएँ': 357,
 'परिचित': 358,
 'मिलिए': 359,
 'लापता': 360,
 'पाँचवे': 361,
 'बृहस्पति': 362,
 'कोमा': 363,
 'किसको': 364,
 'ग़ुस्से': 365,
 'मारे': 366,
 'बयान': 367,
 'तुमने': 368,
 'सालगिरह': 369,
 'लेती': 370,
 'जूतों': 371,
 'क्र': 372,
 'गोलार्धों': 373,
 'समुंदर': 374,
 'लिखो': 375,
 'ट्रेफ़िक': 376,
 'टौम': 377,
 'समझ': 378,
 'जाए': 379,
 'A': 380,
 'तारे': 381,
 '१९९६': 382,
 'चीज़ें': 383,
 'करते': 384,
 'लेआऊँ': 385,
 'जियामिंग': 386,
 'श्वार्झनेगर': 387,
 'सर': 388,
 'ट्रोल': 389,
 'शराब': 390,
 'प्रदर्शन': 391,
 'प्रकट': 392,
 'रहना': 393,
 'गेंदबाज़ी': 394,
 'आपको': 395,
 'सब': 396,
 'स्विमसूट': 397,
 'स्थानिक': 398,
 'विश्वयुद्ध': 399,
 'बाली': 400,
 'मौत': 401,
 'रिहाई': 402,
 'दम': 403,
 'हमें': 404,
 'हँसाना': 405,
 'कॉन्सर्ट': 406,
 'बैटमैन': 407,
 'दोनों': 408,
 'मिलीं': 409,
 'तादाशी': 410,
 'चाहें': 411,
 'बीमारों': 412,
 'वर्षा': 413,
 'लिखे': 414,
 'अल': 415,
 'आर्थर': 416,
 'निर्दयी': 417,
 'बांधी': 418,
 'जज्बे': 419,
 'शोक': 420,
 'दाढ़ी': 421,
 'हकला': 422,
 'लेखकों': 423,
 'पूछूं': 424,
 'कासिम': 425,
 'सतत': 426,
 'भरेगा': 427,
 'परिस्तिथियों': 428,
 'पेट': 429,
 'क्रोध': 430,
 'मशहूर': 431,
 'यामादा': 432,
 'स्वीकारेगा': 433,
 'पहेली': 434,
 'पंद्रहवीं': 435,
 'उत्पाद': 436,
 'फेंकने': 437,
 'पाँव': 438,
 'राजधानीयां': 439,
 'स्थल': 440,
 'हर': 441,
 'टीम': 442,
 'अनहोनी': 443,
 'वो': 444,
 'करदिआ': 445,
 'हैसियत': 446,
 'चश्मा': 447,
 'कामकाज': 448,
 'टाई': 449,
 '७५': 450,
 'बिताई': 451,
 'रहोगे': 452,
 'बर्ट': 453,
 'खिल': 454,
 'वार': 455,
 'समझेंगे': 456,
 'कन्नड़': 457,
 'हवाई': 458,
 'कविताएँ': 459,
 'भाग्य': 460,
 'देशी': 461,
 'रिफ्रेश': 462,
 'फारसी': 463,
 'जँचती': 464,
 'पत्नी': 465,
 'फ़िदा': 466,
 'सहयोग': 467,
 'लौडा': 468,
 'छिप': 469,
 'पिकाचु': 470,
 'बलों': 471,
 'मेड्रिड': 472,
 'बुरगुंदीयाई': 473,
 'रोज': 474,
 'जांच': 475,
 'गाल': 476,
 'चूम': 477,
 'डराती': 478,
 'शत्रु': 479,
 'बजाते': 480,
 'बदबू': 481,
 'टी': 482,
 'खर्चना': 483,
 'संदेस': 484,
 'बचाने': 485,
 'स्मिथ': 486,
 'पट्टियाँ': 487,
 'विमान': 488,
 'बढ़ो': 489,
 'दल': 490,
 'अनुवाद': 491,
 'ब्रेड': 492,
 'ईसप': 493,
 'गे': 494,
 'घूर': 495,
 'स्थान': 496,
 'सवेरे': 497,
 'चुप': 498,
 'ऑस्ट्रेल्या': 499,
 'धीमे': 500,
 'ओपन': 501,
 'रेस': 502,
 'बुद्धी': 503,
 'रेपुबलिका': 504,
 'भेजो': 505,
 'इनका': 506,
 'मॉली': 507,
 'बोलनी': 508,
 'आटा': 509,
 'पोतियां': 510,
 'मेहमान': 511,
 'रिओ': 512,
 'लागु': 513,
 'मंगाऊँ': 514,
 'थप्पड़': 515,
 'बैठा': 516,
 'डराने': 517,
 'गप': 518,
 'कोरिया': 519,
 'कृप्या': 520,
 'आमंत्रण': 521,
 'निकला': 522,
 'गुलाब': 523,
 'युल': 524,
 'जाएगी': 525,
 'प्रधानमंत्री': 526,
 'बुद्ध': 527,
 'उबासी': 528,
 'देखा': 529,
 'साँस': 530,
 'ज़िन्दाबाद': 531,
 'युक्रेनी': 532,
 'दुश्मनों': 533,
 'पैक': 534,
 'प्रकार': 535,
 'टिकिट': 536,
 'हालचाल': 537,
 'भौंका': 538,
 'रवि': 539,
 'चाहूंगी': 540,
 'राजाओं': 541,
 'प्रेमी': 542,
 'दूधवाला': 543,
 'बेहद': 544,
 'बताउँगी': 545,
 'महाराष्ट्र': 546,
 'दादीजी': 547,
 'चट्टान': 548,
 'सहनशीलता': 549,
 'मोबी': 550,
 'बुरा': 551,
 'बाताऊँगा': 552,
 'पार्श्व': 553,
 'आसान': 554,
 'मसीह': 555,
 'बेआराम': 556,
 'लेकिन': 557,
 'संन्यास': 558,
 'जनतंत्र': 559,
 'किला': 560,
 'रोना': 561,
 'बाय': 562,
 'आकछू': 563,
 'लक्सेमबोर्ग': 564,
 'अच्छा': 565,
 'बुला': 566,
 'बोतलों': 567,
 'ताईवान': 568,
 'गेट': 569,
 'अधिक': 570,
 'जोख़िम': 571,
 'लिखना': 572,
 'भाग्यशाली': 573,
 'अखबारों': 574,
 'पास': 575,
 'अटक': 576,
 'वाद्य': 577,
 'मिनिटों': 578,
 'गरीब': 579,
 'घनिष्ठ': 580,
 'रोमैंटिक': 581,
 'ग्रह': 582,
 'पाती': 583,
 'खान': 584,
 'अंगूठी': 585,
 'तेज़': 586,
 'ग़लतियों': 587,
 'जानि': 588,
 'अल्जीरिया': 589,
 'जटिल': 590,
 'वॉरेन': 591,
 'ऋगवेद': 592,
 'स्वयं': 593,
 'देस': 594,
 'गैस': 595,
 'पिकचर': 596,
 'सुधारिए': 597,
 'कबाब': 598,
 'जिसमें': 599,
 'सिगार': 600,
 'तोदाइजी': 601,
 'क्योतो': 602,
 'घुमा': 603,
 'बुलाई': 604,
 'जीती': 605,
 'नारियल': 606,
 'समस्याएं': 607,
 'झुकाएं': 608,
 'थी': 609,
 'बरसी': 610,
 'पुआ': 611,
 'प्रसिद्ध': 612,
 'गैरेज': 613,
 'ख़ज़ाना': 614,
 'कौशल': 615,
 'उच्चार': 616,
 'चित': 617,
 'शांत': 618,
 'बंद': 619,
 'मंदिरों': 620,
 'शिकार': 621,
 'पैसेवाला': 622,
 'सेक्स': 623,
 'बैठो': 624,
 'अंधेरा': 625,
 'किसलिए': 626,
 'पुताई': 627,
 'वफादार': 628,
 'घुसाओ': 629,
 'पाया': 630,
 'मनाते': 631,
 'बतादूँगा': 632,
 'किन्तु': 633,
 'अक्साई': 634,
 'ढूँढना': 635,
 'त्यागपत्र': 636,
 'निकालें': 637,
 'जॉगिंग': 638,
 'सुपर': 639,
 'घटिया': 640,
 'बाल': 641,
 'लुंड': 642,
 'पकाना': 643,
 'सूखा': 644,
 'बीमार': 645,
 'इनमें': 646,
 'पकाएं': 647,
 'जैक': 648,
 'खूनी': 649,
 'गयीं': 650,
 'खिलाफ़': 651,
 'चंगेज़': 652,
 'प्रदेशों': 653,
 'थम': 654,
 'पोस': 655,
 'पूँछ': 656,
 'टाइप': 657,
 'इन्सान': 658,
 'मनवा': 659,
 'बगुले': 660,
 'लेलिया': 661,
 'चाहता': 662,
 'शर्मीली': 663,
 'विपत्तिजनक': 664,
 'हस्ताक्षर': 665,
 'पुल': 666,
 'ऊँचाई': 667,
 'छूट': 668,
 'अनपेक्षित': 669,
 'मज़ाक': 670,
 'छत्तीसगढ़': 671,
 'कॉपीराईट': 672,
 'टिकती': 673,
 'फ़्रैंकफुर्ट': 674,
 'शिफ़्ट': 675,
 'रंडी': 676,
 'आपत्ति': 677,
 'क्योटो': 678,
 'अमरीका': 679,
 'गिरनी': 680,
 'झूठा': 681,
 'किलोमीटर': 682,
 'बीजों': 683,
 'भ्रष्टाचार': 684,
 'जोर': 685,
 'अलविदा': 686,
 'लिखतें': 687,
 'अधिकांश': 688,
 'दौड़ने': 689,
 'रह': 690,
 'पोषण': 691,
 'ज़बरदस्ती': 692,
 'ई': 693,
 'चीज़ों': 694,
 'कड़वा': 695,
 'हस्तमैथुन': 696,
 'टेट्रिस': 697,
 'कैफ़े': 698,
 'कूदते': 699,
 'ताओ': 700,
 'समझता': 701,
 'ध्वज': 702,
 'नियंत्रण': 703,
 'स्नातक': 704,
 'चाहेगा': 705,
 'जीतता': 706,
 'ख़ाली': 707,
 'स्वादिष्ट': 708,
 'करोगे': 709,
 'तेलंगना': 710,
 'भागी': 711,
 'अरेंज': 712,
 'वादी': 713,
 'छटी': 714,
 'लोकप्रिय': 715,
 'अज्ञान': 716,
 'अटका': 717,
 '९': 718,
 'नज़रअंदाज़': 719,
 '(': 720,
 'ठहराया': 721,
 'जानतीं': 722,
 'टेरा': 723,
 'प्रेमपूर्वक': 724,
 'मुझे': 725,
 'यूरोप': 726,
 'लौटकर': 727,
 'कड़ी': 728,
 'होनी': 729,
 'हुकूमत': 730,
 'पेशवा': 731,
 'सिखाती': 732,
 'व्यक्ती': 733,
 'कबसे': 734,
 'केंद्र': 735,
 'पाते': 736,
 'बनो': 737,
 'न्योता': 738,
 'सुनी': 739,
 'तरफ़': 740,
 'बच्चों': 741,
 'चूमने': 742,
 'चालू': 743,
 'मर': 744,
 'ज़हरीली': 745,
 'ज़िरी': 746,
 'कमाल': 747,
 'भौंह': 748,
 'लूंगी': 749,
 'मकान': 750,
 'आसमान': 751,
 'मॉर्ड्रेड': 752,
 'मुच': 753,
 'परमेश्वर': 754,
 'आई': 755,
 'फर्क': 756,
 'डालने': 757,
 'क्षेत्र': 758,
 'सेवाओं': 759,
 'सेव': 760,
 'अकेले': 761,
 'घना': 762,
 'सावधान': 763,
 'ढल': 764,
 'शा': 765,
 'बदलता': 766,
 'शान्ति': 767,
 'दूंगी': 768,
 'ख़ून': 769,
 'लालच': 770,
 'चक्कर': 771,
 '|': 772,
 'करती': 773,
 'मुफ़्त': 774,
 'शुक्रवार': 775,
 'मज़े': 776,
 'डाक': 777,
 'भूखा': 778,
 'वेलेंटाइन': 779,
 'कक्ष': 780,
 'अपनाएं': 781,
 'बनवानी': 782,
 'महँगी': 783,
 'सफ़ल': 784,
 'आख़िरकार': 785,
 'मिलें': 786,
 'सँभाला': 787,
 'मर्ज़ी': 788,
 'ड्रैगन्स': 789,
 'नाक': 790,
 'कुचल': 791,
 'भाषाओं': 792,
 'जमे': 793,
 'होनेवाली': 794,
 'पहाड़ियां': 795,
 'पेड़': 796,
 'सिरों': 797,
 'चुम्मा': 798,
 'बिस्टर': 799,
 'जीकर': 800,
 'लत': 801,
 'क्लास': 802,
 'बंदा': 803,
 'इब्रानी': 804,
 'सँकरी': 805,
 'हठी': 806,
 'अंग्रेज़ी': 807,
 'नील': 808,
 'मारती': 809,
 'रुको': 810,
 'इलाक़ा': 811,
 'कलकत्ता': 812,
 'एंड': 813,
 'बाज़ी': 814,
 'कहूँगा': 815,
 'हिस्सा': 816,
 'रेखाएं': 817,
 'श्रेष्ठ': 818,
 'अलग': 819,
 'तैयारी': 820,
 'जोड़ा': 821,
 'बेबी': 822,
 'चरित्र': 823,
 'परिणाम': 824,
 'सिखाएंगे': 825,
 'आदतें': 826,
 'सुरियाह': 827,
 'दुनिया': 828,
 'कहूं': 829,
 'मोटे': 830,
 'गठरी': 831,
 'साइट': 832,
 'तरफ': 833,
 'तोहफ़ा': 834,
 'पट': 835,
 'बीजिंग': 836,
 'स्वाधीनता': 837,
 'देंगे': 838,
 'विक्टोरिया': 839,
 'दोस्ती': 840,
 'जनसंख्या': 841,
 'मारीओ': 842,
 'बैट': 843,
 'बेसब्री': 844,
 'ज़ोरों': 845,
 'काट': 846,
 'हुएं': 847,
 'सूक': 848,
 'लगने': 849,
 'मंगवाया': 850,
 'टैक्स': 851,
 'विरुद्ध': 852,
 'पूर्वाभास': 853,
 'दहातु': 854,
 'बाढ़': 855,
 'बल्कि': 856,
 'निकम्मा': 857,
 'ज़ेल्डा': 858,
 'मुड़ता': 859,
 'हिसाशी': 860,
 'परस्पर': 861,
 'उत्पादों': 862,
 'गायकों': 863,
 'निकल': 864,
 'कैंडी': 865,
 'पड़ें': 866,
 'लेने': 867,
 'अगले': 868,
 'विशेष': 869,
 'प्रतियोगिता': 870,
 'पूछोगे': 871,
 'वॉरक्राफ्ट': 872,
 'मोहन': 873,
 'कथाओं': 874,
 'आक्रमण': 875,
 'सेहत': 876,
 'नंगे': 877,
 'नसीब': 878,
 'बैठते': 879,
 'हल्का': 880,
 'मे॑': 881,
 'तय': 882,
 'जिससे': 883,
 'बोलतीं': 884,
 'सुपरमैन': 885,
 'अंदेखा': 886,
 'न्यूयॉर्क': 887,
 'दफ़नाया': 888,
 'नगरी': 889,
 'ज़िम्मेदार': 890,
 'खेलतीं': 891,
 '20': 892,
 'इंटरव्यू': 893,
 'चाहेंगी': 894,
 'पायी': 895,
 'वायोला': 896,
 'पुस्तक': 897,
 'पढ़ते': 898,
 'सता': 899,
 'अपने': 900,
 'मारो': 901,
 'लौटें': 902,
 'पियो': 903,
 'जीतने': 904,
 'इंतजार': 905,
 'आँत्वाँ': 906,
 '१८६५': 907,
 'भूतों': 908,
 'कुर्सी': 909,
 'इन्टरनेट': 910,
 'जीव': 911,
 'हित': 912,
 'पढ़ता': 913,
 'ज़हीरुद्दीन': 914,
 'सहायता': 915,
 'केनडी': 916,
 'लगाए': 917,
 'विवाह': 918,
 'असभ्यता': 919,
 'भूख': 920,
 'थका': 921,
 'इसीलिए': 922,
 'मच्छरों': 923,
 'उठाइए': 924,
 'उन्होनें': 925,
 'जानवरों': 926,
 'अध्यापक': 927,
 'रोमानी': 928,
 'बसीं': 929,
 'विच्छेद': 930,
 'नर्क': 931,
 'जिराफ़': 932,
 'कैरन': 933,
 'ऐलान': 934,
 'एकता': 935,
 'जितना': 936,
 'औरडर': 937,
 'तोड़ी': 938,
 'पीकर': 939,
 'परेशानी': 940,
 'चाहूँगा': 941,
 'शरम': 942,
 'मिथुन': 943,
 'मिलेंगीं': 944,
 'भय्या': 945,
 'धोना': 946,
 'बोलते': 947,
 'पालतू': 948,
 'लगेगा': 949,
 'एस्पान्या': 950,
 'तलना': 951,
 'फ़ायदा': 952,
 'खिंचा': 953,
 'शनिवार': 954,
 '१९७४': 955,
 'गायब': 956,
 'रहकर': 957,
 'अड़ियल': 958,
 'उतना': 959,
 'अफ्रीका': 960,
 'मिल': 961,
 'कुशलतापूर्वक': 962,
 'चलाते': 963,
 'होगा': 964,
 'खुली': 965,
 'गै': 966,
 'जाउँगा': 967,
 'प्रतिस्पर्धा': 968,
 'चूहें': 969,
 'पॉलिना': 970,
 'हायाकावा': 971,
 'तेहरान': 972,
 'लिखी': 973,
 'लाती': 974,
 'पहना': 975,
 'मेल': 976,
 'पहन': 977,
 'हीरा': 978,
 'जाऊंगा': 979,
 'ज़ीलंड': 980,
 'शरदोत्सव': 981,
 'मदर': 982,
 'गेंदबाज': 983,
 'देखते': 984,
 'विटामिन': 985,
 'हेनरी': 986,
 'org': 987,
 'देना': 988,
 'छोड़े': 989,
 'मुसलमान': 990,
 'बदलाव': 991,
 'पवित्र': 992,
 'चलें': 993,
 'सिखा': 994,
 'दास': 995,
 'इच्छुक': 996,
 'स्वार्थी': 997,
 'विजेता': 998,
 'सिखाओगी': 999,
 'गति': 1000,
 'मुक्त': 1001,
 'टेक्सी': 1002,
 ...}

In [23]:
print(Vd)

{'आखिरकार': 3, 'ड्राइवर': 4, 'अपनी': 5, 'धोने': 6, 'कांतिमान': 7, 'मोरक्को': 8, 'दूसरा': 9, 'मोन्टकाम': 10, 'योनि': 11, 'उड़ाओ': 12, 'हूँगा': 13, 'पत्रों': 14, 'नरक': 15, 'बोर': 16, 'खोदना': 17, 'आनन्द': 18, 'इससे': 19, 'अभिमानी': 20, 'आगन्तुकों': 21, 'छाया': 22, 'मोहल्ले': 23, 'महंगा': 24, 'तौलिये': 25, 'स्कीर': 26, 'भौतिक': 27, 'बार': 28, 'जीवन': 29, 'सेनापति': 30, 'उम्मीदों': 31, 'खत': 32, 'ब्रिटिश': 33, 'अभिनेता': 34, 'इन्हें': 35, 'जापानीयों': 36, 'नक्षत्रों': 37, 'चाँटे': 38, 'गिरजाघर': 39, 'कपड़ों': 40, 'सुलाना': 41, 'सका': 42, 'गुम': 43, 'गवाह': 44, 'उठाइये': 45, 'गाते': 46, 'मूँह': 47, 'मैंनें': 48, 'मीटर': 49, 'गुलदान': 50, 'हाथों': 51, 'फादिल': 52, 'परोसा': 53, 'चलन': 54, 'पती': 55, 'बौद्ध': 56, 'लडकी': 57, 'दिखता': 58, 'घायलो': 59, 'बारबार': 60, 'शीतयुद्ध': 61, 'बताएँ': 62, 'रोमन': 63, 'आओ': 64, 'नीदरलैंड': 65, 'जंग': 66, 'बजाती': 67, 'जलेगा': 68, 'थक': 69, 'धैर्य': 70, 'अनाथ': 71, 'गोश्त': 72, 'सिंगापुर': 73, 'आसन': 74, 'फोटो': 75, 'कॅलिफॉर्निया': 76, 'कहूँगी': 77, '"': 78, 'पंडित': 79, 'नींव': 80, 'दाँतों': 81, 'दफ़तर': 82, 'कीड़ों': 83, 'अल्जेरियन': 84, 'फ़ोटोकॉपियर': 85, 'बराबरी': 86, 'नव': 87, 'हिरोको': 88, 'जापानी': 89, 'मशरूम': 90, 'ड्राईवर': 91, 'स्क्रैच': 92, 'मकड़ियों': 93, 'कुवैत': 94, 'टकराई': 95, 'बोओगे': 96, 'दुस्साहस': 97, 'सुलेमान': 98, 'नानीजी': 99, 'मारिको': 100, 'बांटती': 101, 'तिनके': 102, 'इछुक': 103, 'प्रभावित': 104, 'रुकूँगी': 105, 'सौंदरराजन': 106, 'रोग': 107, 'बाताऊँगी': 108, 'पढ़ाई': 109, 'ढक': 110, 'अफगानिस्तान': 111, 'कागज़ी': 112, 'धीरे': 113, 'पूछा': 114, 'अंगूर': 115, 'ज़रूरत': 116, 'शब्दों': 117, 'नृत्य': 118, 'बिखेर': 119, 'कुछ': 120, 'श्रिमान': 121, 'नहिं': 122, 'बसने': 123, 'गद्दारी': 124, 'लिंकनने': 125, 'झुकी': 126, 'उन्मूलन': 127, 'दबाकर': 128, 'अश्लीलता': 129, 'संक्षिप्त': 130, 'नाई': 131, 'मूंद': 132, 'नहा': 133, 'मछलीयां': 134, 'नाइट': 135, 'विदोश': 136, 'विकल्पों': 137, 'ढका': 138, 'मचाते': 139, 'चिल्लाना': 140, 'ऊँचा': 141, 'ये': 142, 'धोए': 143, 'रात': 144, 'कपडों': 145, 'ततैयां': 146, 'सस्ते': 147, 'करदें': 148, 'पूजा': 149, 'मोटा': 150, 'काग़ज़': 151, 'हील्स': 152, 'ओलंपिक': 153, 'दुरुपयोग': 154, 'परिश्रम': 155, 'स्वतंत्र': 156, 'श्रम': 157, 'सिक्का': 158, 'होते': 159, 'अवार्ड': 160, 'पड': 161, 'अंधों': 162, 'नानी': 163, 'धरती': 164, 'मील': 165, 'लाऊँगा': 166, 'किया': 167, 'सीखनी': 168, 'निकलो': 169, 'होल्ड': 170, 'आफ़्रिका': 171, 'उगेगा': 172, 'आकाश': 173, 'भाषाएँ': 174, 'पूछ': 175, 'मानती': 176, 'कमी': 177, 'ईंधनों': 178, 'वाइन': 179, 'रुकें': 180, 'म्यूरियल': 181, 'भाईसाहब': 182, 'हीरो': 183, 'सिपाही': 184, 'इजाज़त': 185, 'कर्मचारी': 186, 'अकल': 187, 'सुनती': 188, 'लिफ़ाफ़े': 189, 'विपत्ती': 190, 'संगमरमर': 191, 'बिल्लियाँ': 192, 'बढ़ी': 193, 'बूढ़ी': 194, 'फाइल': 195, 'दिलाई': 196, 'ट्राए': 197, 'जाचुका': 198, 'पौधों': 199, 'मॉडल': 200, 'विद्रोह': 201, 'किम': 202, 'हंस': 203, 'हकों': 204, 'रहीं': 205, 'होठ': 206, 'फुसफुसाकर': 207, 'पहुँचे': 208, 'गुना': 209, 'संदेश': 210, 'सम्पर्क': 211, 'मरम्मत': 212, 'रुकते': 213, 'शाँत': 214, 'टाम': 215, 'बेचारा': 216, 'कम': 217, 'चादरें': 218, 'फ़र्नीचर': 219, 'बह': 220, 'ट्रम्पेट': 221, 'बिछाई': 222, 'समझते': 223, 'पुरे': 224, 'निकाली': 225, 'सोवियेत': 226, 'लिस्बन': 227, 'सातवाँ': 228, 'चाकलेट': 229, 'टहलें': 230, 'श्रीलंका': 231, 'गाओ': 232, 'माँगा': 233, 'द': 234, 'पैग़ाम': 235, 'कॉफ़ी': 236, 'पहुँचाया': 237, 'थूकेगा': 238, 'घंटे': 239, 'कौआ': 240, 'पोंछो': 241, 'क्षण': 242, 'कबूतर': 243, 'बैठने': 244, 'घास': 245, 'विध्यार्थी': 246, 'ß': 247, 'सिखाए': 248, 'ऑफ़': 249, 'स्थापित': 250, 'दिखाता': 251, 'छुएँ': 252, 'गोली': 253, 'कीचड़': 254, 'इस्त्री': 255, 'इराक़': 256, 'काटकर': 257, 'चावी': 258, 'सही': 259, 'सितंबर': 260, 'ज़माने': 261, 'थामने': 262, 'केन': 263, 'नर्म': 264, 'लिपटा': 265, 'नाम': 266, 'रहा': 267, 'स्थित': 268, 'जाएं': 269, 'चपटी': 270, 'बाघ': 271, 'नियंत्रित': 272, 'ऐक्टिनियम': 273, '०००': 274, 'खेद': 275, 'पीया': 276, 'सिक्कों': 277, 'ज़मीर': 278, 'सवार': 279, 'मुझमें': 280, 'आवाज़': 281, 'सकता': 282, 'आपका': 283, 'मलाई': 284, 'आइए': 285, 'सीता': 286, 'मुताबिक': 287, 'अकेलापन': 288, 'साम्राज्य': 289, 'पर': 290, 'लाईं': 291, 'किसान': 292, 'गोलियों': 293, 'मिनटों': 294, 'डालर': 295, 'ब्लॉगर': 296, 'सीधे': 297, 'वीरान': 298, 'कायदे': 299, 'दूँगी': 300, 'करदो': 301, 'बहिष्कार': 302, 'अभी': 303, 'कार्यकर्म': 304, 'कमाता': 305, 'पैरों': 306, 'खींच': 307, 'सेइचो': 308, 'उच्चारण': 309, 'बनातीं': 310, 'माँगे': 311, 'अच्छाई': 312, 'कछुए': 313, 'दिखा': 314, 'ऊटपटाँग': 315, 'सोकर': 316, 'बारी': 317, 'खोलूँ': 318, 'लॅपटॉप': 319, 'हंसो': 320, 'बाएँ': 321, 'तालियां': 322, 'युवा': 323, 'नौ': 324, 'डरपोक': 325, 'गायिका': 326, 'रेखा': 327, 'पनाह': 328, 'कार्यालय': 329, 'घायल': 330, 'सटिया': 331, 'भुला': 332, 'आते': 333, 'डायरी': 334, 'चुकीं': 335, 'बॉस्टन': 336, 'बाप': 337, 'येरुशलयिम': 338, 'ख़रीदी': 339, 'शक': 340, 'पढ़नी': 341, 'प्रशंसक': 342, 'चुनने': 343, 'दिखाईए': 344, 'इस': 345, 'उपहार': 346, 'इच्छानुसार': 347, 'ईश्वर': 348, 'उबले': 349, 'आइंस्टीन': 350, 'समझोगी': 351, 'सिखाई': 352, 'रुकिए': 353, 'धर्माधिकरण': 354, 'बताएं': 355, 'बताइये': 356, 'शुभकामानाएँ': 357, 'परिचित': 358, 'मिलिए': 359, 'लापता': 360, 'पाँचवे': 361, 'बृहस्पति': 362, 'कोमा': 363, 'किसको': 364, 'ग़ुस्से': 365, 'मारे': 366, 'बयान': 367, 'तुमने': 368, 'सालगिरह': 369, 'लेती': 370, 'जूतों': 371, 'क्र': 372, 'गोलार्धों': 373, 'समुंदर': 374, 'लिखो': 375, 'ट्रेफ़िक': 376, 'टौम': 377, 'समझ': 378, 'जाए': 379, 'A': 380, 'तारे': 381, '१९९६': 382, 'चीज़ें': 383, 'करते': 384, 'लेआऊँ': 385, 'जियामिंग': 386, 'श्वार्झनेगर': 387, 'सर': 388, 'ट्रोल': 389, 'शराब': 390, 'प्रदर्शन': 391, 'प्रकट': 392, 'रहना': 393, 'गेंदबाज़ी': 394, 'आपको': 395, 'सब': 396, 'स्विमसूट': 397, 'स्थानिक': 398, 'विश्वयुद्ध': 399, 'बाली': 400, 'मौत': 401, 'रिहाई': 402, 'दम': 403, 'हमें': 404, 'हँसाना': 405, 'कॉन्सर्ट': 406, 'बैटमैन': 407, 'दोनों': 408, 'मिलीं': 409, 'तादाशी': 410, 'चाहें': 411, 'बीमारों': 412, 'वर्षा': 413, 'लिखे': 414, 'अल': 415, 'आर्थर': 416, 'निर्दयी': 417, 'बांधी': 418, 'जज्बे': 419, 'शोक': 420, 'दाढ़ी': 421, 'हकला': 422, 'लेखकों': 423, 'पूछूं': 424, 'कासिम': 425, 'सतत': 426, 'भरेगा': 427, 'परिस्तिथियों': 428, 'पेट': 429, 'क्रोध': 430, 'मशहूर': 431, 'यामादा': 432, 'स्वीकारेगा': 433, 'पहेली': 434, 'पंद्रहवीं': 435, 'उत्पाद': 436, 'फेंकने': 437, 'पाँव': 438, 'राजधानीयां': 439, 'स्थल': 440, 'हर': 441, 'टीम': 442, 'अनहोनी': 443, 'वो': 444, 'करदिआ': 445, 'हैसियत': 446, 'चश्मा': 447, 'कामकाज': 448, 'टाई': 449, '७५': 450, 'बिताई': 451, 'रहोगे': 452, 'बर्ट': 453, 'खिल': 454, 'वार': 455, 'समझेंगे': 456, 'कन्नड़': 457, 'हवाई': 458, 'कविताएँ': 459, 'भाग्य': 460, 'देशी': 461, 'रिफ्रेश': 462, 'फारसी': 463, 'जँचती': 464, 'पत्नी': 465, 'फ़िदा': 466, 'सहयोग': 467, 'लौडा': 468, 'छिप': 469, 'पिकाचु': 470, 'बलों': 471, 'मेड्रिड': 472, 'बुरगुंदीयाई': 473, 'रोज': 474, 'जांच': 475, 'गाल': 476, 'चूम': 477, 'डराती': 478, 'शत्रु': 479, 'बजाते': 480, 'बदबू': 481, 'टी': 482, 'खर्चना': 483, 'संदेस': 484, 'बचाने': 485, 'स्मिथ': 486, 'पट्टियाँ': 487, 'विमान': 488, 'बढ़ो': 489, 'दल': 490, 'अनुवाद': 491, 'ब्रेड': 492, 'ईसप': 493, 'गे': 494, 'घूर': 495, 'स्थान': 496, 'सवेरे': 497, 'चुप': 498, 'ऑस्ट्रेल्या': 499, 'धीमे': 500, 'ओपन': 501, 'रेस': 502, 'बुद्धी': 503, 'रेपुबलिका': 504, 'भेजो': 505, 'इनका': 506, 'मॉली': 507, 'बोलनी': 508, 'आटा': 509, 'पोतियां': 510, 'मेहमान': 511, 'रिओ': 512, 'लागु': 513, 'मंगाऊँ': 514, 'थप्पड़': 515, 'बैठा': 516, 'डराने': 517, 'गप': 518, 'कोरिया': 519, 'कृप्या': 520, 'आमंत्रण': 521, 'निकला': 522, 'गुलाब': 523, 'युल': 524, 'जाएगी': 525, 'प्रधानमंत्री': 526, 'बुद्ध': 527, 'उबासी': 528, 'देखा': 529, 'साँस': 530, 'ज़िन्दाबाद': 531, 'युक्रेनी': 532, 'दुश्मनों': 533, 'पैक': 534, 'प्रकार': 535, 'टिकिट': 536, 'हालचाल': 537, 'भौंका': 538, 'रवि': 539, 'चाहूंगी': 540, 'राजाओं': 541, 'प्रेमी': 542, 'दूधवाला': 543, 'बेहद': 544, 'बताउँगी': 545, 'महाराष्ट्र': 546, 'दादीजी': 547, 'चट्टान': 548, 'सहनशीलता': 549, 'मोबी': 550, 'बुरा': 551, 'बाताऊँगा': 552, 'पार्श्व': 553, 'आसान': 554, 'मसीह': 555, 'बेआराम': 556, 'लेकिन': 557, 'संन्यास': 558, 'जनतंत्र': 559, 'किला': 560, 'रोना': 561, 'बाय': 562, 'आकछू': 563, 'लक्सेमबोर्ग': 564, 'अच्छा': 565, 'बुला': 566, 'बोतलों': 567, 'ताईवान': 568, 'गेट': 569, 'अधिक': 570, 'जोख़िम': 571, 'लिखना': 572, 'भाग्यशाली': 573, 'अखबारों': 574, 'पास': 575, 'अटक': 576, 'वाद्य': 577, 'मिनिटों': 578, 'गरीब': 579, 'घनिष्ठ': 580, 'रोमैंटिक': 581, 'ग्रह': 582, 'पाती': 583, 'खान': 584, 'अंगूठी': 585, 'तेज़': 586, 'ग़लतियों': 587, 'जानि': 588, 'अल्जीरिया': 589, 'जटिल': 590, 'वॉरेन': 591, 'ऋगवेद': 592, 'स्वयं': 593, 'देस': 594, 'गैस': 595, 'पिकचर': 596, 'सुधारिए': 597, 'कबाब': 598, 'जिसमें': 599, 'सिगार': 600, 'तोदाइजी': 601, 'क्योतो': 602, 'घुमा': 603, 'बुलाई': 604, 'जीती': 605, 'नारियल': 606, 'समस्याएं': 607, 'झुकाएं': 608, 'थी': 609, 'बरसी': 610, 'पुआ': 611, 'प्रसिद्ध': 612, 'गैरेज': 613, 'ख़ज़ाना': 614, 'कौशल': 615, 'उच्चार': 616, 'चित': 617, 'शांत': 618, 'बंद': 619, 'मंदिरों': 620, 'शिकार': 621, 'पैसेवाला': 622, 'सेक्स': 623, 'बैठो': 624, 'अंधेरा': 625, 'किसलिए': 626, 'पुताई': 627, 'वफादार': 628, 'घुसाओ': 629, 'पाया': 630, 'मनाते': 631, 'बतादूँगा': 632, 'किन्तु': 633, 'अक्साई': 634, 'ढूँढना': 635, 'त्यागपत्र': 636, 'निकालें': 637, 'जॉगिंग': 638, 'सुपर': 639, 'घटिया': 640, 'बाल': 641, 'लुंड': 642, 'पकाना': 643, 'सूखा': 644, 'बीमार': 645, 'इनमें': 646, 'पकाएं': 647, 'जैक': 648, 'खूनी': 649, 'गयीं': 650, 'खिलाफ़': 651, 'चंगेज़': 652, 'प्रदेशों': 653, 'थम': 654, 'पोस': 655, 'पूँछ': 656, 'टाइप': 657, 'इन्सान': 658, 'मनवा': 659, 'बगुले': 660, 'लेलिया': 661, 'चाहता': 662, 'शर्मीली': 663, 'विपत्तिजनक': 664, 'हस्ताक्षर': 665, 'पुल': 666, 'ऊँचाई': 667, 'छूट': 668, 'अनपेक्षित': 669, 'मज़ाक': 670, 'छत्तीसगढ़': 671, 'कॉपीराईट': 672, 'टिकती': 673, 'फ़्रैंकफुर्ट': 674, 'शिफ़्ट': 675, 'रंडी': 676, 'आपत्ति': 677, 'क्योटो': 678, 'अमरीका': 679, 'गिरनी': 680, 'झूठा': 681, 'किलोमीटर': 682, 'बीजों': 683, 'भ्रष्टाचार': 684, 'जोर': 685, 'अलविदा': 686, 'लिखतें': 687, 'अधिकांश': 688, 'दौड़ने': 689, 'रह': 690, 'पोषण': 691, 'ज़बरदस्ती': 692, 'ई': 693, 'चीज़ों': 694, 'कड़वा': 695, 'हस्तमैथुन': 696, 'टेट्रिस': 697, 'कैफ़े': 698, 'कूदते': 699, 'ताओ': 700, 'समझता': 701, 'ध्वज': 702, 'नियंत्रण': 703, 'स्नातक': 704, 'चाहेगा': 705, 'जीतता': 706, 'ख़ाली': 707, 'स्वादिष्ट': 708, 'करोगे': 709, 'तेलंगना': 710, 'भागी': 711, 'अरेंज': 712, 'वादी': 713, 'छटी': 714, 'लोकप्रिय': 715, 'अज्ञान': 716, 'अटका': 717, '९': 718, 'नज़रअंदाज़': 719, '(': 720, 'ठहराया': 721, 'जानतीं': 722, 'टेरा': 723, 'प्रेमपूर्वक': 724, 'मुझे': 725, 'यूरोप': 726, 'लौटकर': 727, 'कड़ी': 728, 'होनी': 729, 'हुकूमत': 730, 'पेशवा': 731, 'सिखाती': 732, 'व्यक्ती': 733, 'कबसे': 734, 'केंद्र': 735, 'पाते': 736, 'बनो': 737, 'न्योता': 738, 'सुनी': 739, 'तरफ़': 740, 'बच्चों': 741, 'चूमने': 742, 'चालू': 743, 'मर': 744, 'ज़हरीली': 745, 'ज़िरी': 746, 'कमाल': 747, 'भौंह': 748, 'लूंगी': 749, 'मकान': 750, 'आसमान': 751, 'मॉर्ड्रेड': 752, 'मुच': 753, 'परमेश्वर': 754, 'आई': 755, 'फर्क': 756, 'डालने': 757, 'क्षेत्र': 758, 'सेवाओं': 759, 'सेव': 760, 'अकेले': 761, 'घना': 762, 'सावधान': 763, 'ढल': 764, 'शा': 765, 'बदलता': 766, 'शान्ति': 767, 'दूंगी': 768, 'ख़ून': 769, 'लालच': 770, 'चक्कर': 771, '|': 772, 'करती': 773, 'मुफ़्त': 774, 'शुक्रवार': 775, 'मज़े': 776, 'डाक': 777, 'भूखा': 778, 'वेलेंटाइन': 779, 'कक्ष': 780, 'अपनाएं': 781, 'बनवानी': 782, 'महँगी': 783, 'सफ़ल': 784, 'आख़िरकार': 785, 'मिलें': 786, 'सँभाला': 787, 'मर्ज़ी': 788, 'ड्रैगन्स': 789, 'नाक': 790, 'कुचल': 791, 'भाषाओं': 792, 'जमे': 793, 'होनेवाली': 794, 'पहाड़ियां': 795, 'पेड़': 796, 'सिरों': 797, 'चुम्मा': 798, 'बिस्टर': 799, 'जीकर': 800, 'लत': 801, 'क्लास': 802, 'बंदा': 803, 'इब्रानी': 804, 'सँकरी': 805, 'हठी': 806, 'अंग्रेज़ी': 807, 'नील': 808, 'मारती': 809, 'रुको': 810, 'इलाक़ा': 811, 'कलकत्ता': 812, 'एंड': 813, 'बाज़ी': 814, 'कहूँगा': 815, 'हिस्सा': 816, 'रेखाएं': 817, 'श्रेष्ठ': 818, 'अलग': 819, 'तैयारी': 820, 'जोड़ा': 821, 'बेबी': 822, 'चरित्र': 823, 'परिणाम': 824, 'सिखाएंगे': 825, 'आदतें': 826, 'सुरियाह': 827, 'दुनिया': 828, 'कहूं': 829, 'मोटे': 830, 'गठरी': 831, 'साइट': 832, 'तरफ': 833, 'तोहफ़ा': 834, 'पट': 835, 'बीजिंग': 836, 'स्वाधीनता': 837, 'देंगे': 838, 'विक्टोरिया': 839, 'दोस्ती': 840, 'जनसंख्या': 841, 'मारीओ': 842, 'बैट': 843, 'बेसब्री': 844, 'ज़ोरों': 845, 'काट': 846, 'हुएं': 847, 'सूक': 848, 'लगने': 849, 'मंगवाया': 850, 'टैक्स': 851, 'विरुद्ध': 852, 'पूर्वाभास': 853, 'दहातु': 854, 'बाढ़': 855, 'बल्कि': 856, 'निकम्मा': 857, 'ज़ेल्डा': 858, 'मुड़ता': 859, 'हिसाशी': 860, 'परस्पर': 861, 'उत्पादों': 862, 'गायकों': 863, 'निकल': 864, 'कैंडी': 865, 'पड़ें': 866, 'लेने': 867, 'अगले': 868, 'विशेष': 869, 'प्रतियोगिता': 870, 'पूछोगे': 871, 'वॉरक्राफ्ट': 872, 'मोहन': 873, 'कथाओं': 874, 'आक्रमण': 875, 'सेहत': 876, 'नंगे': 877, 'नसीब': 878, 'बैठते': 879, 'हल्का': 880, 'मे॑': 881, 'तय': 882, 'जिससे': 883, 'बोलतीं': 884, 'सुपरमैन': 885, 'अंदेखा': 886, 'न्यूयॉर्क': 887, 'दफ़नाया': 888, 'नगरी': 889, 'ज़िम्मेदार': 890, 'खेलतीं': 891, '20': 892, 'इंटरव्यू': 893, 'चाहेंगी': 894, 'पायी': 895, 'वायोला': 896, 'पुस्तक': 897, 'पढ़ते': 898, 'सता': 899, 'अपने': 900, 'मारो': 901, 'लौटें': 902, 'पियो': 903, 'जीतने': 904, 'इंतजार': 905, 'आँत्वाँ': 906, '१८६५': 907, 'भूतों': 908, 'कुर्सी': 909, 'इन्टरनेट': 910, 'जीव': 911, 'हित': 912, 'पढ़ता': 913, 'ज़हीरुद्दीन': 914, 'सहायता': 915, 'केनडी': 916, 'लगाए': 917, 'विवाह': 918, 'असभ्यता': 919, 'भूख': 920, 'थका': 921, 'इसीलिए': 922, 'मच्छरों': 923, 'उठाइए': 924, 'उन्होनें': 925, 'जानवरों': 926, 'अध्यापक': 927, 'रोमानी': 928, 'बसीं': 929, 'विच्छेद': 930, 'नर्क': 931, 'जिराफ़': 932, 'कैरन': 933, 'ऐलान': 934, 'एकता': 935, 'जितना': 936, 'औरडर': 937, 'तोड़ी': 938, 'पीकर': 939, 'परेशानी': 940, 'चाहूँगा': 941, 'शरम': 942, 'मिथुन': 943, 'मिलेंगीं': 944, 'भय्या': 945, 'धोना': 946, 'बोलते': 947, 'पालतू': 948, 'लगेगा': 949, 'एस्पान्या': 950, 'तलना': 951, 'फ़ायदा': 952, 'खिंचा': 953, 'शनिवार': 954, '१९७४': 955, 'गायब': 956, 'रहकर': 957, 'अड़ियल': 958, 'उतना': 959, 'अफ्रीका': 960, 'मिल': 961, 'कुशलतापूर्वक': 962, 'चलाते': 963, 'होगा': 964, 'खुली': 965, 'गै': 966, 'जाउँगा': 967, 'प्रतिस्पर्धा': 968, 'चूहें': 969, 'पॉलिना': 970, 'हायाकावा': 971, 'तेहरान': 972, 'लिखी': 973, 'लाती': 974, 'पहना': 975, 'मेल': 976, 'पहन': 977, 'हीरा': 978, 'जाऊंगा': 979, 'ज़ीलंड': 980, 'शरदोत्सव': 981, 'मदर': 982, 'गेंदबाज': 983, 'देखते': 984, 'विटामिन': 985, 'हेनरी': 986, 'org': 987, 'देना': 988, 'छोड़े': 989, 'मुसलमान': 990, 'बदलाव': 991, 'पवित्र': 992, 'चलें': 993, 'सिखा': 994, 'दास': 995, 'इच्छुक': 996, 'स्वार्थी': 997, 'विजेता': 998, 'सिखाओगी': 999, 'गति': 1000, 'मुक्त': 1001, 'टेक्सी': 1002, 'मुर्मू': 1003, 'टीवी': 1004, 'रोक': 1005, 'रक्त': 1006, 'वेब': 1007, 'चालक': 1008, 'जन्मा': 1009, 'काटते': 1010, 'एस': 1011, 'धार्मिक': 1012, 'सदैव': 1013, 'डालें': 1014, 'यूमी': 1015, 'छाल': 1016, 'अपमानजनक': 1017, 'पंद्रह': 1018, 'त्रासदी': 1019, 'दिवाली': 1020, 'इमाम': 1021, 'अपौइंटमेंट': 1022, '१९६०': 1023, 'अम्रीकी': 1024, 'चिल्लाया': 1025, 'उन्हें': 1026, '७': 1027, '१७४७': 1028, 'दिखाई': 1029, 'मद्य': 1030, 'चुटकुलें': 1031, 'चैनल': 1032, 'मध्ये': 1033, 'ग्वातेमाला': 1034, 'निर्मूलन': 1035, 'दूरी': 1036, 'इंसान': 1037, 'बोल': 1038, 'पढ़': 1039, 'ईनाम': 1040, 'फिले': 1041, 'थें': 1042, 'सिढ़ियों': 1043, 'जन्म': 1044, 'पढ़तें': 1045, 'प्रयत्न': 1046, 'ऐसी': 1047, 'पैंट': 1048, 'मनुष्यों': 1049, 'कतई': 1050, 'संत्रा': 1051, 'सामने': 1052, 'दोनो': 1053, 'सिखाया': 1054, 'हिरण': 1055, 'लगते': 1056, 'सत्रह': 1057, 'इज़्ज़त': 1058, 'बचायी': 1059, 'सूरज': 1060, 'चाईनिज': 1061, 'मरे': 1062, 'खड़ा': 1063, 'प्रतिक्रिया': 1064, 'मुर्गियाँ': 1065, 'बेशक': 1066, 'अकलमंद': 1067, 'गुरू': 1068, 'घ्राण': 1069, 'चढ़ेगा': 1070, 'अनुपस्तिथि': 1071, 'फॉन्ट': 1072, 'सवाल': 1073, 'डायल': 1074, 'जाउंगी': 1075, 'ओकोनोमियाकी': 1076, 'अवसर': 1077, 'चोद': 1078, 'खाया': 1079, 'ज़्यादातर': 1080, 'पेटू': 1081, 'करवाऊँगा': 1082, 'कराया': 1083, 'भेजा': 1084, 'बैठीं': 1085, 'सिंधु': 1086, 'बिस्तरों': 1087, 'क्षमा': 1088, 'सूट': 1089, 'आंध्र': 1090, 'ताकतवर': 1091, 'भाषांतर': 1092, 'स्कैनर': 1093, 'गिलहरियाँ': 1094, 'कॉनरी': 1095, 'मूँगफलियाँ': 1096, 'पर्वत': 1097, 'लड़ूंगा': 1098, 'सूर्य': 1099, 'भ्रम': 1100, 'नाडु': 1101, 'फ़ाईल': 1102, 'तेल': 1103, 'एलर्जी': 1104, 'शरद': 1105, 'अम्हारी': 1106, 'घर': 1107, 'उसमें': 1108, 'कर्णाटक': 1109, 'साउथ': 1110, 'फ़ोन': 1111, 'भाईचारे': 1112, 'पिकासो': 1113, 'दियें': 1114, 'छत्रपति': 1115, 'चली': 1116, 'कहेगा': 1117, 'चोदते': 1118, 'हरा': 1119, 'मज़दूर': 1120, 'अक़्ल': 1121, 'लुई': 1122, 'हिलने': 1123, 'बत्तियाँ': 1124, 'सँकरे': 1125, 'कुफल': 1126, 'डरा': 1127, 'मौलिकता': 1128, 'खुशखबर': 1129, 'इंजन': 1130, 'ज़ू': 1131, 'तीनों': 1132, 'गाडियों': 1133, 'ठहरे': 1134, 'चखाऊँगा': 1135, 'आदर्श': 1136, 'डॉनत': 1137, 'ऑस्ट्रिया': 1138, 'दीवारें': 1139, 'तस्वीरों': 1140, 'असंभव': 1141, 'बेचता': 1142, 'ऐन': 1143, 'शरमा': 1144, 'हड़बड़ी': 1145, 'पक्का': 1146, 'तट': 1147, 'नाचेगा': 1148, 'एनबीए': 1149, 'डम्प': 1150, 'मुम्बई': 1151, 'क्या': 1152, 'बनायी': 1153, 'फेंका': 1154, 'बिल्ला': 1155, 'बिज्जू': 1156, 'मर्द': 1157, 'आर्नोल्ड': 1158, 'प्रतिक्षा': 1159, 'कैमरा': 1160, 'निर्धनता': 1161, 'पटक': 1162, 'युक्रेन': 1163, 'थोडे': 1164, 'लापरवाही': 1165, 'यंत्र': 1166, 'मुस्कान': 1167, 'राष्ट्रीय': 1168, 'प्रोग्राम': 1169, 'से': 1170, 'पतंग': 1171, 'हिरोशी': 1172, 'भट्टा': 1173, 'गएं': 1174, 'साडे': 1175, 'समूह': 1176, 'योनी': 1177, 'निशान': 1178, 'उपग्रह': 1179, 'फिरसे': 1180, 'ख़तरे': 1181, 'ट्रेन': 1182, 'भेजने': 1183, 'तरीका': 1184, '४': 1185, 'आऊँगी': 1186, 'अंकल': 1187, 'पकाती': 1188, 'फ़्लैट': 1189, 'बिकता': 1190, 'जानीमानी': 1191, 'बालों': 1192, 'मुस्कुराए': 1193, 'जाएँगे': 1194, 'आमदनी': 1195, 'ख़रगोश': 1196, 'यातायात': 1197, 'भिन्न': 1198, 'सीखना': 1199, 'मंज़िल': 1200, 'गाजर': 1201, 'वज़नदार': 1202, 'जानें': 1203, 'Tatoeba': 1204, 'देकर': 1205, 'रखिएगा': 1206, 'बोलेगा': 1207, 'पीड़ित': 1208, 'परिक्रमा': 1209, 'बलात्कार': 1210, 'निश्चय': 1211, 'अफ़्रीका': 1212, 'लंबा': 1213, 'जोन्स': 1214, 'जाया': 1215, 'करनी': 1216, 'मिलती': 1217, 'कंठशोथ': 1218, 'पुष्टि': 1219, 'संभालने': 1220, 'पडा': 1221, 'विकास': 1222, 'सोचो': 1223, 'मालुम': 1224, 'अंपायर': 1225, 'ढंग': 1226, 'अहसास': 1227, 'वैर': 1228, 'बॉलीवूड': 1229, 'आमने': 1230, 'लाऊँगी': 1231, 'खाड़ी': 1232, 'तेलुगू': 1233, 'कुबलई': 1234, 'संकोच': 1235, 'भूलें': 1236, 'दवाईयों': 1237, 'बदाम': 1238, 'काटती': 1239, 'बचाइए': 1240, 'रखेंगे': 1241, 'अस्वीकार': 1242, 'सार्थक': 1243, 'तैरती': 1244, 'घडी़': 1245, 'स्लोवाक': 1246, 'पैसा': 1247, 'जोन': 1248, 'बाल्टी': 1249, 'रेस्तराँ': 1250, 'अहंकारी': 1251, 'हिट': 1252, 'विष्ठा': 1253, 'देवेंद्र': 1254, 'विस्फोट': 1255, 'बोलने': 1256, 'बेसबॉल': 1257, 'जिमखाने': 1258, 'दर': 1259, 'आएँगे': 1260, 'बताईये': 1261, 'दक्षिण': 1262, 'दानें': 1263, 'भारत': 1264, 'एस्पेरान्तो': 1265, 'मज़बूत': 1266, 'विडूर': 1267, 'बधाई': 1268, 'मंगोलीयाई': 1269, 'सूज़ैन': 1270, 'है॑': 1271, 'संपत्ति': 1272, 'लगें': 1273, 'सोचने': 1274, 'दिवस': 1275, 'नतीजे': 1276, 'पकड़ीं': 1277, 'दीदी': 1278, 'जचता': 1279, 'कबार': 1280, 'माथे': 1281, 'किसके': 1282, 'हॉलीवुड': 1283, 'धूल': 1284, 'चुरा': 1285, 'अनुसार': 1286, 'कक्षागृह': 1287, 'सापेक्षवाद': 1288, 'बाबर': 1289, 'लाईन': 1290, 'सर्बिया': 1291, 'चंगुल': 1292, 'फैले': 1293, 'फिसला': 1294, 'इसीलिये': 1295, 'बीटल्स': 1296, 'सहवाग': 1297, 'पकाया': 1298, 'साधा': 1299, 'अड्डे': 1300, 'पीने': 1301, 'इसे': 1302, 'नीति': 1303, 'हिंदुस्तान': 1304, 'हिमाचल': 1305, 'सुनूँगी': 1306, 'चेला': 1307, 'क़ैदियों': 1308, 'नाशी': 1309, 'कविताएं': 1310, '७२': 1311, 'लुका': 1312, 'डार्सी': 1313, 'कैनरी': 1314, 'सौ': 1315, 'सारे': 1316, 'सीखेंगी': 1317, 'सरासर': 1318, 'हाँ': 1319, 'ब्रिटेन': 1320, 'बनाने': 1321, 'बनाए': 1322, 'चमड़े': 1323, 'सयाने': 1324, 'केले': 1325, 'ऐरो': 1326, 'विकासशील': 1327, 'स्वीस': 1328, 'खरगोश': 1329, 'सौंदर्य': 1330, 'चोदता': 1331, 'इसका': 1332, 'पड़ा': 1333, 'तुरंत': 1334, 'नौकर': 1335, 'हाशिमोतो': 1336, 'दूत': 1337, 'बैठूं': 1338, 'तेरी': 1339, 'घेरा': 1340, 'देने': 1341, 'मछलियों': 1342, 'किजिए': 1343, 'साहसी': 1344, 'কোনো': 1345, 'नज़ारा': 1346, 'चालाकी': 1347, 'लंच': 1348, 'कुल': 1349, 'झाड़ी': 1350, 'नाकामयाब': 1351, 'प्रभावशाली': 1352, 'नामों': 1353, 'कालोनी': 1354, 'उल्टा': 1355, 'आपातकाल': 1356, 'हस्पताल': 1357, 'झगड़ों': 1358, 'बनाते': 1359, 'आया': 1360, 'करनेवाली': 1361, 'सुनाओ': 1362, 'पासपोर्ट': 1363, 'मुस्कुराओ': 1364, 'उसीको': 1365, 'ज़ाहिर': 1366, 'निगाहें': 1367, 'हराया': 1368, 'मिश्रण': 1369, 'वेबसाइट': 1370, 'सालों': 1371, 'खदशा': 1372, 'क्यूँ': 1373, 'एशियाइयों': 1374, 'रुकूँगा': 1375, 'जातीं': 1376, 'सात': 1377, 'प्रुशिया': 1378, 'नियम': 1379, 'समाज': 1380, '८': 1381, 'काँच

In [24]:
len(Vd)

7072

In [25]:
def convert_hindi_tokens_to_ids(hindi_sent):
    return [Vd[token]for token in hindi_sent]

In [26]:
data["DstSent"]=data["DstSent"].apply(lambda x:convert_hindi_tokens_to_ids(x))

In [27]:
data.head()

,SrcSent,DstSent
0,"[4159, 23, 14018, 19, 460, 230, 5]","[181, 1797, 5357, 5420, 4538, 1431, 2146, 6324..."
1,"[4159, 23, 14018, 19, 460, 230, 5]","[181, 1797, 5357, 5420, 4538, 6324, 4335]"
2,"[2855, 16, 48, 296, 26963, 7, 140, 5]","[4784, 345, 828, 2632, 4928, 290, 6387, 5981, ..."
3,"[466, 751, 31, 17, 1837, 5]","[2237, 6700, 964, 4335]"
4,"[27, 3041, 25, 5]","[6574, 5983, 4418, 6979, 5797, 6324, 4335]"

In [28]:
def insert_sos_token_id(hindi_sent_token_ids):
    return [1] + hindi_sent_token_ids

In [29]:
data["DstSentInput"]=data["DstSent"].apply(lambda x: insert_sos_token_id(x))

In [30]:
data.head()

,SrcSent,DstSent,DstSentInput
0,"[4159, 23, 14018, 19, 460, 230, 5]","[181, 1797, 5357, 5420, 4538, 1431, 2146, 6324...","[1, 181, 1797, 5357, 5420, 4538, 1431, 2146, 6..."
1,"[4159, 23, 14018, 19, 460, 230, 5]","[181, 1797, 5357, 5420, 4538, 6324, 4335]","[1, 181, 1797, 5357, 5420, 4538, 6324, 4335]"
2,"[2855, 16, 48, 296, 26963, 7, 140, 5]","[4784, 345, 828, 2632, 4928, 290, 6387, 5981, ...","[1, 4784, 345, 828, 2632, 4928, 290, 6387, 598..."
3,"[466, 751, 31, 17, 1837, 5]","[2237, 6700, 964, 4335]","[1, 2237, 6700, 964, 4335]"
4,"[27, 3041, 25, 5]","[6574, 5983, 4418, 6979, 5797, 6324, 4335]","[1, 6574, 5983, 4418, 6979, 5797, 6324, 4335]"

In [31]:
def insert_eos_token_id(hindi_sent_token_ids):
    return hindi_sent_token_ids +[2]

In [32]:
data["DstSentLabel"]=data["DstSent"].apply(lambda x: insert_eos_token_id(x))

In [33]:
data.head()

,SrcSent,DstSent,DstSentInput,DstSentLabel
0,"[4159, 23, 14018, 19, 460, 230, 5]","[181, 1797, 5357, 5420, 4538, 1431, 2146, 6324...","[1, 181, 1797, 5357, 5420, 4538, 1431, 2146, 6...","[181, 1797, 5357, 5420, 4538, 1431, 2146, 6324..."
1,"[4159, 23, 14018, 19, 460, 230, 5]","[181, 1797, 5357, 5420, 4538, 6324, 4335]","[1, 181, 1797, 5357, 5420, 4538, 6324, 4335]","[181, 1797, 5357, 5420, 4538, 6324, 4335, 2]"
2,"[2855, 16, 48, 296, 26963, 7, 140, 5]","[4784, 345, 828, 2632, 4928, 290, 6387, 5981, ...","[1, 4784, 345, 828, 2632, 4928, 290, 6387, 598...","[4784, 345, 828, 2632, 4928, 290, 6387, 5981, ..."
3,"[466, 751, 31, 17, 1837, 5]","[2237, 6700, 964, 4335]","[1, 2237, 6700, 964, 4335]","[2237, 6700, 964, 4335, 2]"
4,"[27, 3041, 25, 5]","[6574, 5983, 4418, 6979, 5797, 6324, 4335]","[1, 6574, 5983, 4418, 6979, 5797, 6324, 4335]","[6574, 5983, 4418, 6979, 5797, 6324, 4335, 2]"

In [34]:
data.drop(labels=[data.columns[1]],axis=1,inplace=True)

In [35]:
data.head()

,SrcSent,DstSentInput,DstSentLabel
0,"[4159, 23, 14018, 19, 460, 230, 5]","[1, 181, 1797, 5357, 5420, 4538, 1431, 2146, 6...","[181, 1797, 5357, 5420, 4538, 1431, 2146, 6324..."
1,"[4159, 23, 14018, 19, 460, 230, 5]","[1, 181, 1797, 5357, 5420, 4538, 6324, 4335]","[181, 1797, 5357, 5420, 4538, 6324, 4335, 2]"
2,"[2855, 16, 48, 296, 26963, 7, 140, 5]","[1, 4784, 345, 828, 2632, 4928, 290, 6387, 598...","[4784, 345, 828, 2632, 4928, 290, 6387, 5981, ..."
3,"[466, 751, 31, 17, 1837, 5]","[1, 2237, 6700, 964, 4335]","[2237, 6700, 964, 4335, 2]"
4,"[27, 3041, 25, 5]","[1, 6574, 5983, 4418, 6979, 5797, 6324, 4335]","[6574, 5983, 4418, 6979, 5797, 6324, 4335, 2]"

In [36]:
data.columns

Index(['SrcSent', 'DstSentInput', 'DstSentLabel'], dtype='object')

In [37]:
X=list(data["SrcSent"])
Y_input=list(data["DstSentInput"])
Y_label=list(data["DstSentLabel"])

In [38]:
X_tensor=[torch.tensor(tokenised_eng_sent_ids) for tokenised_eng_sent_ids in X]
Y_input_tensor=[torch.tensor(tokenised_hin_sent_ids) for tokenised_hin_sent_ids in Y_input]
Y_label_tensor=[torch.tensor(tokenised_hin_sent_ids) for tokenised_hin_sent_ids in Y_label]

In [39]:
X_padded=torch.nn.utils.rnn.pad_sequence(X_tensor,batch_first=True)
Y_padded_input=torch.nn.utils.rnn.pad_sequence(Y_input_tensor,batch_first=True)
Y_padded_label=torch.nn.utils.rnn.pad_sequence(Y_label_tensor,batch_first=True)

In [40]:
Ns=X_padded.shape[1]
Nd=Y_padded_label.shape[1]

In [41]:
Ns

68

In [42]:
Nd

68

In [43]:
class Encoder(torch.nn.Module):

    def __init__(self,src_lang_lang_vocab_size,word_embedding_dim):
        super(Encoder,self).__init__()
        self.first_embedding_layer=torch.nn.Embedding(num_embeddings = src_lang_vocab_size,
                                                      embedding_dim = word_embedding_dim)
        self.second_lstm_layer=torch.nn.LSTM(input_size=word_embedding_dim,
                                             hidden_size=word_embedding_dim,
                                             batch_first=True)
    def forward(self,X_padded_mini_batch):

        first_embedding_layer_out=self.first_embedding_layer(X_padded_mini_batch)
        encoder_output, (final_encoder_output,final_cell_state) = self.second_lstm_layer(first_embedding_layer_out)
        
        return encoder_output,(final_encoder_output,final_cell_state)

In [44]:
class Decoder(torch.nn.Module):
    
    def __init__(self,dst_lang_vocab_size,word_embedding_dim):
        super(Decoder,self).__init__()
        
        self.first_embedding_layer+torch.nn.Embedding(num_embeddings = src_lang_vocab_size,
                                                      embedding_dim = word_embedding_dim)
        self.second_lstm_layer=torch.nn.LSTM(input_size=word_embedding_dim,
                                             hidden_size=word_embedding_dim,
                                             batch_first=True)
        self.prediction_layer=torch.nn.Linear(in_features=word_embedding_dim,out_features=dst_lang_vocab_size)
        self.prediction_layer_activation=torch.nn.Softmax(dim=2)
        
        
    def forward(self,Y_padded_input_mini_batch,final_encoder_output,final_cell_state):

        first_embedding_layer_out=self.first_embedding_layer(Y_padded_input_mini_batch)
        decoder_lstm_layer_out, (final_decoder_lstm_layer_out,final_cell_state) = self.second_lstm_layer(first_embedding_layer_out,
                                                                                                     final_encoder_output,
                                                                                                      final_cell_state)
        prediction=self.prediction_layer_activation(self.prediction(decoder_lstm_layer_out))
        return prediction, (final_decoder_lstm_layer_out,final_cell_state)